### ISSUE TITLE
Working with new Amazon S3 Regions doesn't work due to missing V4 authentication scheme

### ISSUE THREAD

**Issue by philippdhh** [strongloop/loopback-component-storage#101]
Hi,

while the loopback-component-storage seems to work well with most AWS S3 regions it does not work with regions created later than 2014 like the Frankfurt region in Europe.

The following error is returned:

{
  "error": {
    "name": "InvalidRequest",
    "status": 400,
    "message": "The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.",
    "code": "InvalidRequest",
    "time": "2015-12-02T23:30:05.289Z",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 60,
    "stack": "InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.\n    at Request.extractError (C:\\Users\\Philipp\\WebstormProjects\\GroupTravelMgrJs\\node_modules\\loopback-component-storage\\node_modules\\pkgcloud\\node_modules\\aws-sdk\\lib\\services\\s3.js:343:35)\n    at Request.callListeners
[........]
  }
}

It seems to be related to this issue: http://stackoverflow.com/questions/26533245/the-authorization-mechanism-you-have-provided-is-not-supported-please-use-aws4

Best,
Philipp

**Comment by ataraxus** [comment]
Same issue here.

**Comment by ataraxus** [comment]
I hade a quick glance onto the impl. it seems to be an upstream issue. loopback-component-storage uses internally pkgcloud: https://www.npmjs.com/package/pkgcloud
There is already a version 1.2.0-alpha.0 but bumping the version loopback-component-storage uses (1.1.0) didn't help

**Comment by ataraxus** [comment]
Hey @philippdhh, 

I fixed it for me now. See here whats was the issue: https://github.com/aws/aws-sdk-js/issues/829
for Frankfurt you have just to set the "correct" region: 
```javascript
 var publicHandler = new StorageService(
    {
      provider: 'amazon',
      region: "eu-central-1",
      keyId: "",
      key: ""
    });
```
I think it can be closed now

**Comment by philippdhh** [comment]
Thank you very much.
I will try it tomorrow.

**Comment by ataraxus** [comment]
so did it worked for you?

**Comment by richardpringle** [comment]
@philippdhh did @ataraxus' solution work? I am going to close the issue, but please re-open the issue and mention me directly if the problem persists!
