### ISSUE TITLE
Restrict overwriting files

### ISSUE THREAD

**Issue by martinjuhasz** [strongloop/loopback-component-storage#106]
If i use the upload method i should be able to restrict the system to not overwrite existing files.

Since i can't determine the filename before uploading (if i don't set it myself) i cannot check if the file exists before uploading it to its wanted destination and so the file gets overwritten.

is there a way to restrict this without the need to change the codebase? should such an option be implemented?

**Comment by DenJohX** [comment]
+1, at the moment there seems to be impossible.

I'm investigating one way to implement it without using component-storage

**Comment by richardpringle** [comment]
:+1: 

I think there should be a `overwrite: false` option (or something along those lines).

**Comment by cfjedimaster** [comment]
I just ran into this myself and frankly was shocked this wasn't baked in. I'd like to propose though that overwrite be more than just true/false. ColdFusion supports  a few options for this case:

1) skip (ie, no error, but no write)
2) error 
3) overwrite
4) makeUnique - this is done by simply appending a value to the filename to make it unique

**Comment by kalimulhaq** [comment]
+1

**Comment by cfjedimaster** [comment]
@kalimulhaq - I added a new feature for this to - it was added about a week or so ago - docs should be updated soon. Basically I just support a "always make it unique" option which was easiest.
