### ISSUE TITLE
Flaw in the architecture of the fetching file 

### ISSUE THREAD

**Issue by robinskumar73** [strongloop/loopback-component-storage#107]
`Loopback-component-storage` is best for fetching files when the file is getting stored at `FileSystem` but when the file is being stored at `Amazon` or some third party cloud service then fetching file becomes drastically slow as first a connection is made at server then another connection is made at cloud provider and then file is fetched which makes the whole process very slow.

I think instead of that there should be some method like `getUrl()` or something which generated the `signed url` for cloud providers. So that file can be fetched directly from cloud server without compromising with the speed. When using `loopback-component-storage` you can't use any `CDN` providers service because data is fetched not directly thus it takes more time for fetching the data.

**Comment by byavv** [comment]
+1

**Comment by raymondfeng** [comment]
@robinskumar73 Interesting idea. Do you know if most cloud providers support signed urls?

**Comment by robinskumar73** [comment]
@raymondfeng I think there should be two method for generating url `getSignedUrl()` for those like Amazon Cloud Front or `Amazon S3` for generating signed url  and `getUnsignedUrl`  and a config in `datasource.json`  to check whether to generate only `signedUrl()`.

`datasource.json`
`
....
....
"Image": {
    "name": "Image",
    "connector": "loopback-component-storage",
    "provider": "amazon",
    "key": "SECRET KEY",
    "keyId": "SECRET KEY ID",
    "cdn": {
        "amazon": {
            "container": "Container Name On Which CDN is applied",
            "keyPairId": "CDN CLOUD PAIR KEY",
            "url": "http://xxxxxxx.cloudfront.net",
            "generateSignedUrl": true,
            "generateUnSignedUrl": false,
            "privateKeyPath": "../amazon-private-key.pem"
        }
    }
  }`


Here in  `datasource.json`  file there should be a `CDN` like property to support CDN like features.

**Comment by andrewwiik** [comment]
did we ever get a signedUrl feature?
