### ISSUE TITLE
Custom metadata

### ISSUE THREAD

**Issue by bobbyhubbard** [strongloop/loopback-component-storage#11]
Loving loopback and the storage service. Any appetite toward an accompanying custom metadata storage option? I'm finding that in order to group files together or apply any type of filter on the files for application use, I obviously have to store a separate reference to the file paths in a data source. Would be amazingly awesome if I could include tag(s) with the upload. 

Potential benefits
1. Ability to query uploaded files by tag value. (e.g. where tags in ["2014", "org", "gallery"])
2. Ability to query uploads by implied meta (e.g. where type == 'jpeg', where size > 10000, etc). 
3. I imagine for the filesystem provider that getFiles is just an 'ls' on the directory. This could instead be a much more performant db listing vs file io on the app server host.

**Comment by cadesalaberry** [comment]
Hi there, is this being worked on right now ?

**Comment by Lughino** [comment]
+1

**Comment by tention** [comment]
@raymondfeng any plan on this since it was mentioned within the roadmap since 2014

**Comment by handonam** [comment]
What can we do to finalize the ideas and get this started?

**Comment by cadesalaberry** [comment]
Hello @raymondfeng, the question still remains. Could we get an answer ?

**Comment by sebastianfelipe** [comment]
Is there a solution to that?

**Comment by cadesalaberry** [comment]
Hi again tiny bot,

thanks a lot for your answer, however, the question still remains unanswered...

Do you think any of @kjdelisle @jannyHou @loay @b-admike @ssh24 @virkt25 @dhmlau could give us an answer?

Thank you tiny bot,

Cheers

**Comment by dhmlau** [comment]
@raymondfeng @bajtos , any thoughts?

**Comment by bajtos** [comment]
Well, as @raymondfeng commented on Apr 30, 2014, this feature was on our roadmap, but as we can all see, it never made it to our short-term backlog. I am afraid we won't have bandwidth to implement this feature ourselves any time soon, but we are happy to help you along the way if you decide to contribute the implementation yourself.
