### ISSUE TITLE
Rename a file in container

### ISSUE THREAD

**Issue by whispers16** [strongloop/loopback-component-storage#114]
I'm trying to upload 2 files with the same name and extension in a container, but the problem is that one file overrides the other one, I want to have them in the same container, so... is there any way to rename files while or after i'm uploading the files? 

thanks!

**Comment by whispers16** [comment]
solved with #41

**Comment by cfjedimaster** [comment]
I think this needs to be re-opened. There is a solution (although I couldn't tell by reading #41 how to implement it), but this needs to be added to the documentation. The fact that the *default* behavior is to overwrite files on upload is a serious problem imo, and we don't even *say* that's the behavior in the docs.

**Comment by whispers16** [comment]
If it's of help this is how I implemented:
1. in boot files I created a file named storage.js
2. then I made this code:
```
'use strict';

var path = require('path');

module.exports = function(app) {

  var ds = app.loopback.createDataSource({
    connector: require('loopback-component-storage'),
    provider: 'filesystem',
    root: path.join(__dirname, '../', '../', 'storage'),

    // getFilename will be called multiple times for each "part" of the form upload
    getFilename: function (origFilename, req, res) {
        var origFilename = origFilename.name;
        // optimisticly get the extension
        var parts = origFilename.split('.'),
            extension = parts[parts.length-1];

        // Using a local timestamp + user id in the filename (you might want to change this)
        var newFilename = (new Date()).getTime()+'_'+parts[parts.length-2]+'.'+extension;
        return newFilename;
    }
  });
  var container = ds.createModel('container');
  app.model(container);
};
```

**Comment by cfjedimaster** [comment]
How would I do that though when I've defined my storage DS in datasources.json?

**Comment by whispers16** [comment]
@cfjedimaster  Sorry for answering late, yeah indeed I actually defined my storage DS in datasources.json e.g.
```
"storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "provider": "filesystem",
    "root": "./storage",
    "maxFileSize": "52428800"
  }
```
The thing is, when you create the code that I posted before in the boot files, it only renames the file  everytime you upload something ("current timestamp" + the filename) so even though  they have both the same name and are in the same container, the storage.js changes the name's file before to be uploaded.

**Comment by cfjedimaster** [comment]
I'm sorry - but I'm not quite getting it. Are you saying you defined the DS twice?

**Comment by cfjedimaster** [comment]
As an aside, I'd like to argue for re-opening this ticket. I feel very strongly that the *default* behavior should be to not overwrite, and that renaming should be baked in. (As an option perhaps, but baked in.)

**Comment by cfjedimaster** [comment]
I already have a ticket open for that - I forgot: https://github.com/strongloop/loopback-component-storage/issues/172

**Comment by voipAsteriskGuy** [comment]
@cfjedimaster 

in this way you can use the getFilename function without the need of declare twice the datastore.
datasource.json 
`
  "storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "provider": "filesystem",
    "root": "./server/storage"
  }
`
then i made a boot script with the name container.js and added the next function:
`
module.exports = function(app) {
  app.dataSources.storage.connector.getFilename = function (origFilename, req, res) {
        var origFilename = origFilename.name;
        var parts = origFilename.split('.'),
        extension = parts[parts.length-1];
        var newFilename = (new Date()).getTime()+'_'+parts[parts.length-2]+'.'+extension;
        return newFilename;
  }
};
`
I also think that the default behavior must not overwrite the files and i think that this function and the way to use it must be better documented i looked on 3 or 4 issues before figure out how to make this functionality.

**Comment by cfjedimaster** [comment]
Thanks for sharing this. I've decided it's time to put up or shut up - I'm going to work on a PR to add the functionality I want - at least for the filesystem provider.

**Comment by miquipuig** [comment]
I have a similar issue but this solution doesn't suit my needs. I need to rename the files but using context data. I use LoopBackContext and only know one way to recover data from context. In container.js model I use:

`module.exports = function(Container) {

    Container.afterRemote('upload', function(ctx, res, next) {`

How  can I use context data to rename a file?

Thanks a lot!  And sorry for my basic english...
