### ISSUE TITLE
Needs revision on documentation for storageService.download 

### ISSUE THREAD

**Issue by saggafarsyad** [strongloop/loopback-component-storage#115]
I was writing a remote method in my user model for downloading image profile. I'm using [storageService.download](https://apidocs.strongloop.com/loopback-component-storage/#storageservice-prototype-download).  I read all documentations [here](https://docs.strongloop.com/display/public/LB/Storage+component) and [here](https://apidocs.strongloop.com/loopback-component-storage/#storageservice-prototype-download)  but nothing works. It always returns the same error `res.type is not a function etc`. 

I almost give up until I take a look at the [base code](https://github.com/strongloop/loopback-component-storage/blob/master/lib/storage-service.js), and then I found that the parameters should be `storageService.download(container, file, req, res, cb)`. 

It would be more helpful if the documentation is always updated. Thank you

**Comment by superkhau** [comment]
@crandmck ^

**Comment by crandmck** [comment]
Fixed with 6bf93614515788f31c9c0dcf400096a33d59eb72.

@superkhau @raymondfeng Can we please republish to npm to update the API doc?

**Comment by superkhau** [comment]
@crandmck I just tried to publish, need perms. @raymondfeng Can you add me (username: `superkhau`) or do the publish yourself?

**Comment by jaime-franco** [comment]
Hi guys, thanks this help me, but i think documentation is out of date.

**Comment by saggafarsyad** [comment]
@jaime-franco Yeah it seems not yet updated

**Comment by crandmck** [comment]
Right, docs will not be updated until the package is re-published to npm.  

Unfortunately, neither I nor @superkhau seems to have publish rights.
@raymondfeng Ping again--can you please give Simon publish rights for this repo or just publish it?

**Comment by raymondfeng** [comment]
@superkhau You should have the permission now

**Comment by superkhau** [comment]
Thanks @raymondfeng. @crandmck 1.8.0 is published on NPM now.

**Comment by crandmck** [comment]
Thanks @superkhau. I noticed that I made a small mistake in the doc comment, so I corrected it.  The signature is correct, so it's not critical to republish immediately.

**Comment by superkhau** [comment]
@crandmck NP, just let me know when u need a repub.
