### ISSUE TITLE
Download errors expose stacktrace in production.

### ISSUE THREAD

**Issue by zanemcca** [strongloop/loopback-component-storage#118]
When a download fails the stacktrace is included.

This can be recreated by trying to download a non-existent file from a non-existent container while using S3 as the backend. 

Even without S3 it is clear that the error handler is not using the `remoting` error handler. It should be so that the stacktrace can be enabled and disable in `config.json` and so that the errorHandler can be replaced when necessary.

@richardpringle can you help?

**Comment by richardpringle** [comment]
@loay will your error handler work solve this?

**Comment by loay** [comment]
@zanemcca  @richardpringle 
It should. Here is the main discussion to give you an idea about the new error handling in production. 
https://github.com/strongloop/loopback/issues/1650
