### ISSUE TITLE
[Feature]: Disable remote methods for Container model.

### ISSUE THREAD

**Issue by richardpringle** [strongloop/loopback-component-storage#120]
Related: strongloop/loopback#2189

Right now, you can't disable any of the individual methods. @dongmai supplied the initial request.

**Comment by nickell** [comment]
I stumbled upon this issue too but I found an awesome recipe by @dashby3000 [here](https://github.com/dashby3000/recipe-s3-image-uploader) that details how to resize images before uploading to S3. In that recipe he disables several remote methods on containers. Using that technique, here's a snippet that would disable all remote methods, comment out as needed!

```javascript
Container.disableRemoteMethod('createContainer', true)
Container.disableRemoteMethod('getContainer', true)
Container.disableRemoteMethod('getContainers', true)
Container.disableRemoteMethod('destroyContainer', true)
Container.disableRemoteMethod('download', true)
Container.disableRemoteMethod('removeFile', true)
Container.disableRemoteMethod('getFiles', true)
Container.disableRemoteMethod('getFile', true)
Container.disableRemoteMethod('upload', true)
```

**Comment by richardpringle** [comment]
Thanks @nickell!
