### ISSUE TITLE
LoopBack-AngularJS SDK + Storage.upload method

### ISSUE THREAD

**Issue by TheRossman** [strongloop/loopback-component-storage#130]
Hi all,

I am using loopback-component-storage to connect to an Amazon s3 bucket without issue.  Creating and listing containers works great.  Using the AngularJS Client SDK generated by lb-ng, I can see that there was a method generated to upload a file for my container model, ie. Container.upload().

My issue is that I cannot figure out the correct params to pass to that upload method to get a successful upload.

I have tried: 

```
      Container.upload({container: 's3bucketname'}, {file: file}).$promise.then(function(){
        console.log('file uploaded!');
      });
```

which will generate a call to the server in my network console but no file ever uploads.  If I replace that call with the ng-file-upload Uploader, things work fine.  Should the angular generated upload method work, and if so, what are the expected params?   I was not able to find this documented anywhere.

Thanks!

**Comment by richardpringle** [comment]
Hey @TheRossman, checkout [this example](https://github.com/strongloop/loopback-example-storage/tree/master/example-2.0). It should contain everything you need. 

If it doesn't, let me know. I will keep the issue open until I hear back.

Good luck!

(I agree the documentation could improve at lease for the example)

**Comment by TheRossman** [comment]
Hi Richard,

Thanks for the reply.  Unfortunately, that example doesn't use the generated AngularJS client sdk to do the upload, they install another angular component (Angular File Upload) to handle the upload.  I was hoping to use the generated Angular client SDK and not have to bring in a 3rd party module just to handle this one thing.

Also, using a third party lib means I have to know the url to my loopback endpoint, where if I use the generated SDK it "just knows" where the endpoints are  :)

Cheers,
mark

**Comment by richardpringle** [comment]
Ah, I see. @TheRossman, can you fork a [loopback-sandbox](https://github.com/strongloop/loopback-sandbox), reproduce in there (using file-system instead of S3) and share the link?

Let me know if you can't reproduce on the file-system and we'll figure out how to move forward.

**Comment by TheRossman** [comment]
Hi @richardpringle ,

I have forked your repo and replicated the issue here: https://github.com/TheRossman/loopback-sandbox

You should be able to clone that repo, run node ., then browse to http://0.0.0.0:3000/index.html to see the issue.

Relevant code is:
https://github.com/TheRossman/loopback-sandbox/blob/master/client/scripts/controllers/main.js#L16-L18

Thank you, please let me know if you have any questions!  

- mark

**Comment by richardpringle** [comment]
@TheRossman I don't have an answer for you at this point. Maybe @davidcheung has some ideas by chance?

I threw a feature label on here as it would be good for that to work out of the box. If I were you, I would look at the other example and see if you same thing to work on its own.

**Comment by TheRossman** [comment]
@richardpringle thanks again for your reply.  I am not 100% sure, but I think I am just calling the upload method with the wrong params.

If I use an alternative file uploader like in the [official example](https://github.com/strongloop/loopback-example-storage/tree/master/example-2.0) the upload works, but it means that I have to have an additional third party library for the uploading, as well as some extra code to figure out what the loopback api root url is.

If I can use the built in angular client sdk method it makes everything a lot cleaner, and, like I said, I don't think there is actually any bug here I just can't figure out what params to pass the upload method to get it to work.

Thanks again I really appreciate the response!  Only recently started using loopback but it's amazing!

**Comment by richardpringle** [comment]
@TheRossman, I meant take a look at the example to see what params are being passed to `upload`, although I'm not sure how difficult it is to do that. This module is not quite as easy to debug as other loopback modules. If you can get `upload` working without Angular, it should be relatively straight forward after that that.

**Comment by TheRossman** [comment]
@richardpringle Right, yeah, I have made some deductions on that front.
I've figured out that I have to pass two params to the method to generate a request with a valid POST url, and the first one has to be an object with container: <containerName> in it (per my original comment).  What to pass in the second param seems a bit of a mystery.  Thanks again  :)

**Comment by richardpringle** [comment]
Changing the name of this issue from `AngularJS SDK + Storage.upload() method` to `LoopBack-AngularJS SDK + Storage methods` so that the feature request represents more than just one method.

**Comment by TheRossman** [comment]
Actually the other methods still work ok!  ie. I can use the Angular client sdk to list containers, etc.  it is just the upload part that seems to be an issue  :)

**Comment by davidcheung** [comment]
@TheRossman I'm not quite sure either, haven't tried it myself
maybe this example would be useful (this example might be abit old, so probably some of the implementation would be deprecated (explorer))
https://github.com/strongloop/loopback-component-storage/blob/2d313ac25bedfb12948ef5b5d0518d0e100a3470/example-2.0/client/controllers.js#L8-L20
>https://github.com/strongloop/loopback-sdk-angular/issues/22#issuecomment-214590979

/cc @richardpringle

**Comment by richardpringle** [comment]
@TheRossman, changed the title back... that's weird that it only doesn't work for that one method.

**Comment by TheRossman** [comment]
@richardpringle I think it's because file uploading in angular is a little different than normal POSTing of a string or other basic type.  Sadly I don't know enough about this to work on a PR!

@davidcheung thanks yeah, I was able to use that example to get a third party uploading working, the downsides to going this route, I have documented above.  I guess I will have to stick with this approach for now.

Thanks to you both for your responses!

**Comment by pbrain19** [comment]
Has this been solved? someone needs to write some docs explaining how to use the angular SDK with file uploads. In particular I created a relationship such that a customer(base of User) can have many images. The SDK generates a customer.images.create() method but i can't for the life of me figure out how to use it. All I get is incorect input type for data of type file. Someone help :)

**Comment by TheRossman** [comment]
You have to use a third party uploader, theres no way to upload a file via Loopbacks Angular SDK.

**Comment by pbrain19** [comment]
Wait what? that doesn't sound right to me. hows the file upload happening? like is it application/json? or what?

**Comment by pbrain19** [comment]
Can someone please define what the storage api is suppose to accept. I keep getting this error.

**Comment by superkhau** [comment]
@pbrain19 https://apidocs.strongloop.com/loopback-component-storage/

What do you guys suggest to improve the docs? @crandmck can make the changes accordingly.

**Comment by mansonkibe** [comment]
@TheRossman  any solution to this as for now? I didn't want to take the approach of using a third party uploader. I wanted to stick with angular 2 SDK. But i have ` onUpdate(stove:BlImages){
        //if(this.stoveForm.valid){
        this.submitted = true;

        let stoveImage = this.fStoveImage.nativeElement;
        let formImage = this.fFormImage.nativeElement;
        let blImage = this.fBlImage.nativeElement;
        let idImage = this.fIdImage.nativeElement;




        if (stoveImage.files && stoveImage.files[0]) {

            this.stoveImage = stoveImage.files[0];
        }

        const imageFile: File = this.stoveImage;

        const formData = new FormData();
        formData.append('stoveImage',imageFile,imageFile.name);


        let headers: Headers = new Headers();
        headers.append('Accept', 'multipart/form-data');
        headers.append('Content-Type', 'application/x-www-form-urlencoded');

        this.attachmentApi.upload("test",formData, formData, headers ).subscribe(response =>{
            console.log(response)
        }) }`

but i can't seem to figure out a way

**Comment by TheRossman** [comment]
@mansonkibe Honestly I didn't look at this any further beyond my last post.  I only needed to know that for a particular project and I've never had to use it again since, so I just used the workaround (third party lib) even though it wasn't ideal.
