### ISSUE TITLE
error uploading to amazon s3

### ISSUE THREAD

**Issue by 0101adm** [strongloop/loopback-component-storage#136]
loopback 2.29.0
loopback-storage-component 1.8.0

i can list containers using the explorer.  

uploading using the built-in `upload` throws the below error.

`
Failed to create a multipart upload on S3: {"message":"The request signature we calculated does not match the signature you provided. Check your key and signing method.","stack":"SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.\n    at Request.extractError (/Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/services/s3.js:524:35)\n    at Request.callListeners (/Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\n    at Request.emit (/Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\n    at Request.emit (/Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/request.js:615:14)\n    at Request.transition (/Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/request.js:22:10)\n    at AcceptorStateMachine.runTo (/Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/state_machine.js:14:12)\n    at /Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/state_machine.js:26:10\n    at Request.<anonymous> (/Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/request.js:38:9)\n    at Request.<anonymous> (/Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/request.js:617:12)\n    at Request.callListeners (/Users/aaron/Documents/dev/mobilityre/apps/my-home-api/node_modules/aws-sdk/lib/sequential_executor.js:115:18)","code":"SignatureDoesNotMatch","region":null,"time":"2016-06-30T18:35:25.110Z","requestId":"76AC63AA6E2CF17F","extendedRequestId":"ynyMctijtZu1aSpzv9VyKx1ZtbviSiy2FVYc0xYuOTwY/6mpldSnzbj1QgeGkHoDYwO4Xn+sh0w=","statusCode":403,"retryable":false,"retryDelay":1.064461306668818}
`

**Comment by migreva** [comment]
Was there a resolution to this issue? We're seeing the same problem and don't know where to go with it

**Comment by 0101adm** [comment]
Looking at my code, I created a seperate remote method that uses S3's upload method.

```
LbAmazonS3.beforeRemote('doUpload', (context, unused, next) => {
		LbAmazonS3.app.dataSources['amazonS3-dsn'].connector.getFilename = (file, req, res) => {
			return req.query.bucket;
	   }

	   next();
	});

	LbAmazonS3.doUpload = (bucket, req, res, callback) => {
		LbAmazonS3.upload(req, res, { container: 'my-home-bucket' }, (err, data) => {
			if (err) {
				callback(err, {
					status: false,
					message: 'Could Not Upload'
				});
			} else {
				callback(null, {
					status: true
				});
			}
		});
	}

	LbAmazonS3.remoteMethod('doUpload', {
		accepts: [
			{ arg: 'bucket', type: 'string', required: true },
			{ arg: 'req', type: 'object', 'http': {source: 'req' }},
        	{ arg: 'res', type: 'object', 'http': {source: 'res' }}
		],
		returns: { arg: 'payload', type: 'object' },
		http: { verb: 'post' }
	});
```

**Comment by portokallidis** [comment]
So you should open the issue again as it seems that loopback-component-storage actually doesn't work with s3

**Comment by portokallidis** [comment]
I am investigating this and it seems working if you specify "region": "eu-central-1" on your frankfurt buckets, but we need more generalized solution 
It seems that it fails for regions that only handle AWS Signature Version 4 so you can lookup your [AWS regions](http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region) and add this property to the datasources configuration `"region":"AWS_REGION_CODE"`

Also this probably means that the guys at [pkgcloud](https://github.com/pkgcloud/pkgcloud) should make the appropriate changes and this is not relevant to loopback-component-storage.

@0101adm thanks for the quick response and you can keep the issue open until they fix the issue and then you upgrade to pkgcloud 1.5 to resolve and close the issue .

**Comment by muskan21** [comment]
Is there a resolution? I tried using "region":"---" in my datasource.json but it's still not working.
