### ISSUE TITLE
Wrong Content-Type for Files with '/' in file name

### ISSUE THREAD

**Issue by geekguy** [strongloop/loopback-component-storage#140]
In the download API, If we have `/` is filename, because of [this](https://github.com/strongloop/loopback-component-storage/blob/master/lib/storage-handler.js#L252) line, content type will be wrong.

``` javascript
// implementation of res.type function
res.type = function contentType(type) {
  var ct = type.indexOf('/') === -1
    ? mime.lookup(type)
    : type;

```

So if we have '/' is the file name, content type will be set to filename directly without mime lookup.

For now we have added encodeURIComponent. 

Not sure if that's a proper fix. https://github.com/RentoMojo/loopback-component-storage/commit/ecf68198116452f2af510f95156d54f73c5261cd

**Comment by superkhau** [comment]
@geekguy Would you like to submit a PR with an accompanying test and link it to this issue? Let's get it resolved there instead.

**Comment by geekguy** [comment]
@superkhau : Sure.
