### ISSUE TITLE
strongloop-storage-component ignores callback parameter in download method

### ISSUE THREAD

**Issue by drbolsen** [strongloop/loopback-component-storage#147]
Hi there,

I've been wrangling with the storage components for a bit now, just discovered that download method in storage-handler module ignores callback parameter completely, e.g. calling

```
Container.download (container, filename, req, res, function (err, result) {
   // this part will never fire at all
});
```
Strangely enough the master branch handles the callback correctly, compare **1.9.0**

```
          res.type(fileName);

          reader.pipe(res);
          reader.on('error', function(err) {
            handleError(res, err);
          });
        }
```

and the same in **master** branch

```
      res.type(fileName);

      reader.pipe(res);
      reader.on('error', function(err) {
        handleError(res, err);
      });
      reader.on('end', function() {
        cb();
      });
```

**Comment by richardpringle** [comment]
@drbolsen, we need to release a new version of the module. In the meantime, you can use master.

**Comment by drbolsen** [comment]
Yep, we ended up using master for time being, it would be good to have it back again via "npm install".

**Comment by richardpringle** [comment]
@drbolsen v1.9.1 was released with the latest code from master
