### ISSUE TITLE
vulnerability in dependency

### ISSUE THREAD

**Issue by jmls** [strongloop/loopback-component-storage#168]
Please note that pkgcloud@1.3.0 uses request@2.40.0, which uses hawk@1.1.1 which has a vulnerablity ( https://nodesecurity.io/advisories/77) 

there is an open issue (https://github.com/pkgcloud/pkgcloud/issues/531), so we need to be aware of this and update to the latest pkgcloud as soon as a patch / version is released

**Comment by siyb** [comment]
Are there any plans on when to update the dependency yet?

**Comment by thanh-taro** [comment]
I'm waiting for it too.

**Comment by superkhau** [comment]
Would one of you like to contribute a PR? I can help get it merged ASAP.

**Comment by siyb** [comment]
I would contribute a PR, is it ok if I update all package dependencies within the PR as well?

**Comment by superkhau** [comment]
@Amir-61 @loay Reassigning you guys to figure out as you it's in your FA -- please TOB as you guys see fit.

**Comment by cse-tushar** [comment]
@Amir-61 @loay @superkhau Fixed in pkgcloud version 1.5.0. https://github.com/pkgcloud/pkgcloud/issues/542 . This can be closed now.
