### ISSUE TITLE
Storage component docs need some serious help

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback-component-storage#170]
Specifically this is the problem. 

The docs tell you to install a component. Ok so far. 

It then explains containers and files. Ok... 

It then tells you to create a datasource. So right away, a person may be confused. Why is a datasource used for this? Typically datasources are how we say "Persist data for so and so model". The connection here is a bit nebulous, but you carry on.

It then tells you how to configure the datasource. Ok, that makes sense too.

Then it goes to this: "Once you create a container"

Say what? How do we create a container? Why do we create a container? 

I'll add that I came into this feature because I wanted to add file support to an *existing* model. So given a Cat API, I want a new property, resume, that represents the cats resume. I think this type of use case (add binary property to a model) will be common, but the docs don't explain how this would be done.

**Comment by cfjedimaster** [comment]
So at this point, I'm at a complete loss. Looking at the example app, I see they have a model called "container". So I added one with no properties, set the datasource to my Storage DS. THe docs don't say to do this, but I did. Reload and I see nothing in the explorer.

**Comment by cfjedimaster** [comment]
So I had a folder called "files" in project root. Above server, client, common, etc. My ds config was:

"root":"./files"

I thought - maybe it needs to be under server. So I moved the folder and changed root to

"root":"./server/files"

and it worked - well not exactly. I had a typo in some code. But the issue is this: LoopBack ignored ./files. It didn't like it and silently failed, which is bad. I'll file an error on that.

**Comment by cfjedimaster** [comment]
Ok, so ... yeah. I've added a container model even though the docs don't necessarily say I have to. I've restarted, but I don't see anything in the explorer.

**Comment by cfjedimaster** [comment]
Ugh. So when adding a *other* datasource, the CLI tells you specifically to NOT include "loopback-component". So I did that. And it added it as "connector":"storage" in datasources.json. So the past 30 minutes have been loss because - afaik - I followed the CLI directions and I should not have. Switching to the full name fixes it.

**Comment by cfjedimaster** [comment]
So in the end, you must have a model. This is implied, but not made clear. The model name then becomes part of the API:

/api/YOURNAMEHERE/stuff

where "stuff" includes what the storage component gives you - container list, file list, etc. 

This part I think is the biggest tripping point. At least it was for me.

**Comment by crandmck** [comment]
Thanks, and I agree the docs need some TLC.  I'll try to work on them, but would really appreciate a PR based on your experiences if you can find the time.  BTW, did the example app help? http://loopback.io/doc/en/lb2/Storage-example.html.

**Comment by cfjedimaster** [comment]
No, because the issue was - imo - the relationship of the model. Ie, what does adding model X do for you? The docs don't really imply that you need to (it kinda does) and it doesn't say what happens when you do - and that is it simply becomes part of the URL and nothing more.

**Comment by cfjedimaster** [comment]
And yes - I can try to wordsmith something. I'm planning a blog post for the StrongBlog, but I can try to help the doc page too.
