### ISSUE TITLE
Filesystem provider does not handle name conflicts

### ISSUE THREAD

**Issue by cfjedimaster** [strongloop/loopback-component-storage#172]
If you are using the filesystem provider and upload a file w/ the same name to the same container, it will overwrite the existing file. 

It would be best, imo, if this were configurable. ColdFusion does a great job of this and lets you specify 3 behaviors:

* throw error
* overwrite
* make unique

With make unique being the typical choice folks make. Since the connector already returns the file name, we could use that to know "Oh, even though I uploaded avatar.jpg, it is now avatar1.jpg".

This could be a simple option specified in datasources.json.

**Comment by csotomon** [comment]
is there any way to define the getFilename function in datasource.json file?

**Comment by hacksparrow** [comment]
Reopening this since this is something that has to be addressed. Tagging as `major` so it is not closed automatically.

**Comment by cfjedimaster** [comment]
A while ago I added support for "makeunique", ie if set to true, automatically make a unique name for the uploaded file (it didn't matter if it was a conflict or not). Technically that doesn't match everything mentioned here, but at least you can use the Storage component now and not worry about conflicts.

**Comment by hacksparrow** [comment]
Yes, indeed it is already implemented. Closing this, will update the docs.
