### ISSUE TITLE
Range undefined error in storage-handler

### ISSUE THREAD

**Issue by nqueued** [strongloop/loopback-component-storage#177]
When trying to download a file, getting an exception that range is undefined in setupPartialDownload function.
```
node_modules\loopback-component-storage\lib\storage-handler.js:270
  var parts = range.replace(/bytes=/, '').split('-');
                                          ^
ReferenceError: range is not defined
```

**Comment by davidtorroija** [comment]
It's happening the same to me but only when I upload an Mp3 file for example this file(it's not related to the max size because I uploaded big images too): http://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3

**Comment by jorafali** [comment]
@davidtorroija 
Your link does work. Does this mean you have found a solution to the problem ?

**Comment by davidtorroija** [comment]
@jorafali No, I did not find a solution yet for this bug, I just post an example url but you should upload an mp3 to local object storage( filesystem) and you going to see this error when you try to see the file using the loopback download endpoint for example:

http://0.0.0.0:3000/api/containers/newFolder/download/media-1479915907919-soundhelix-song-1.mp3

```
/node_modules/loopback-component-storage/lib/storage-handler.js:270
  var parts = range.replace(/bytes=/, '').split('-');
                                          ^

ReferenceError: range is not defined
    at setupPartialDownload (/Users/davidtorroija/workspace/knowbly/widget-composer-sdk/node_modules/loopback-component-storage/lib/storage-handler.js:270:43)
    at /Users/davidtorroija/workspace/knowbly/widget-composer-sdk/node_modules/loopback-component-storage/lib/storage-handler.js:244:5
    at /Users/davidtorroija/workspace/knowbly/widget-composer-sdk/node_modules/loopback-component-storage/lib/providers/filesystem/index.js:261:11
    at /Users/davidtorroija/workspace/knowbly/widget-composer-sdk/node_modules/async-listener/glue.js:188:31
    at FSReqWrap.oncomplete (fs.js:123:15)

```
so the object is properly saved in the folder but you can't access using the "download" endpoint

**Comment by nqueued** [comment]
@jorafali 
The problem is in the exports.download function which is retrieving the range values from the request headers. The value is stored to a local function variable, which cannot be accessed by setupPartialDownload as its scope is outside the setupPartialDownload function.

Since range is undeclared, it throws the exception.

```
exports.download = function(provider, req, res, container, file, cb) {
  var fileName = path.basename(file);
  var params = {
    container: container || req && req.params.container,
    remote: file || req && req.params.file,
  };

  var range = null;

  if (!req) {
    // TODO(rfeng/bajtos) We should let the caller now about the problem!
    return;
  }

  if (req.headers) {
    range = req.headers.range || '';
  }
```

The values for range are not accessible or passed into the function setupPartialDownload function, causing the error.

```
  provider.getFile(params.container, params.remote, function(err, stats) {
    if (err) {
      return cb(processError(err, params.remote));
    }

    setupPartialDownload(params, stats, res);
    download(params);
  });
```

**Comment by hgouveia** [comment]
same issue for me  (1.10.0)

```
/project/node_modules/loopback-component-storage/lib/storage-handler.js:270
  var parts = range.replace(/bytes=/, '').split('-');
              ^

ReferenceError: range is not defined
    at setupPartialDownload (/project/node_modules/loopback-component-storage/lib/storage-handler.js:270:15)
    at /project/node_modules/loopback-component-storage/lib/storage-handler.js:244:5
    at /project/node_modules/loopback-component-storage/lib/providers/filesystem/index.js:261:11
    at /project/node_modules/loopback/node_modules/loopback-context/node_modules/continuation-local-storage/node_modules/async-listener/glue.js:188:31
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by NayWinMyint** [comment]
Solved this issue by passing an extra parameter of _range_ to **setupPartialDownload** function from **provider.getFile** function.

**Comment by anselanza** [comment]
Any workaround for this issue, or is the fix going to be incorporated into a release soon?

**Comment by rahpuser** [comment]
@ole3021 great solution... Do you plan to incorporate a pr into the main project ?

**Comment by itssajan** [comment]
I'm having the same issue with video upload. Any updates on this ?

**Comment by itssajan** [comment]
updated the package and it has solved my issue. Thanks

**Comment by ole3021** [comment]
The strongloop have merged my PR to their code, so the problem should be fixed with the last offical package. can update and check it again.
