### ISSUE TITLE
Optional file upload in container.upload

### ISSUE THREAD

**Issue by saggafarsyad** [strongloop/loopback-component-storage#184]
### Bug or feature request

- [ ] Bug
- [X] Feature request

### Description of feature (or steps to reproduce if bug)
I have a case in my endpoint which file uploading is optional. When I upload the form without file uploaded, it will return "No file content uploaded". It would be great if there is options added such as `{optionalFileUpload: true}` which flags that file uploading is optional.

I think it is possible if I add another condition in line 192 in storage-handler.js
`if (Object.keys(_files).length === 0 && !options.optionalFileUpload) {`

### Expected result
Success uploading form instead of returning No content uploaded error

### Additional information (Node.js version, LoopBack version, etc)
I overcome this by commenting line 197-201 in storage-handler.js. But it will be overwritten when pacakge is updated

**Comment by developermhayden** [comment]
I have this same need for the same reasons (my changes are overwritten on deploy to Heroku).
Is there a way to use my own version of "storage-handler.js" by maybe placing a copy in my mixins folder?

**Comment by Sanbornzhang** [comment]
yes. should be in mixins folder . maybe should be new common lib（do some other logic check[exe,pdf,excel...]）

**Comment by developermhayden** [comment]
@Sanbornzhang It actually wasn't as straight forward as putting in my mixin folder. I am not saying it won't work. I'm saying I had no success doing it that way.

I opted to clone loopback-component-storage, make the change I needed, checked the code into my own private git repo and updated my loopback application's package.json to install loopback-component-storage from my hosted instance.

**Comment by Sanbornzhang** [comment]
@developermhayden loopback-component-storage just upload file. others should give another remote method. upload file -> /xxx/uploadFile API -> do some logic check -> call  loopback-component-storage upload function.
