### ISSUE TITLE
maxFileSize is not working

### ISSUE THREAD

**Issue by NaqeebSial** [strongloop/loopback-component-storage#197]
I have create a file uploading component useing following configuration

```
"storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "allowedContentTypes": ["image/jpg", "image/jpeg", "image/png"],
    "provider": "filesystem",
    "maxFileSize":  "1048576",
    "root": "image"
  }
}
```
When I upload a file whose size is more then maxFileSize server gave me an error
`"maxFileSize exceeded, received 1103821 bytes of field data (max is 1048576)"
`
Its fine but with this error loopback storage component also create image in directory, it should not create image if size is more then maxFileSize.

**Comment by PerfectedTech** [comment]
The stale bot is too aggressive. This is an issue and should remain open.

**Comment by denzelwamburu** [comment]
I agree with @PerfectedTech

**Comment by axul** [comment]
+1

**Comment by maxoux** [comment]
+1

**Comment by artsrunimargaryanfd** [comment]
how can I separate max size and content type for different containers?

**Comment by reyalpsirc** [comment]
This is still happening

**Comment by francobasaglia** [comment]
This's still happening (v3.5.0) any solution??

**Comment by tarun080698** [comment]
This issue still persists, any solutions??
