### ISSUE TITLE
InvalidAccessKeyId with Amazon

### ISSUE THREAD

**Issue by jordymeow** [strongloop/loopback-component-storage#198]
Whatever I have tried, I always get InvalidAccessKeyId. Of course, I have set key and keyId properly, checked the roles, ended up using the admin account directly, etc... It is always InvalidAccessKeyId.

I spent hours googling but nothing much about the component-storage and Amazon recently so I wouldn't be surprised if more people run into this issues as well. It would be nice to know if somebody actually is using the component-storage right now with Amazon. I suspect this might just not be working at all currently, or a parameter (region? server?) might be missing?

**Comment by jordymeow** [comment]
This code **doesn't work**. I get "InvalidAccessKeyId".

```
    var ds = loopback.createDataSource({
      connector: require('loopback-component-storage'),
      provider: 'amazon',
      key: key,
      keyId: keyId
    });
    var container = ds.createModel('container');
    container.getContainers((err, containers) => {
      console.log(err, containers);
    });
```

However, if I do this, **it works** fine.

```
  let client = require('pkgcloud').storage.createClient({
       provider: 'amazon',
       keyId: key,
       key: keyId
    });
    client.getContainers((err, containers) => {
      console.log(err, containers);
    });
```

So I guess this is a problem related to loopback-component-storage, right?

**Comment by Jordi-Mobdala** [comment]
I currently using Amazon S3 with loopback 2 and it works well for me after solve some configuration errors.
First check if keyId and key are in correct order, in my first test I put the value of key in keyId and keyId in key and I get an error.
Second if you are using a S3 bucket in a region with signature version v4 only you can see the next error:
`Failed to create a multipart upload on S3: "message":"The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.`
To solve this error you need to add the "region" field in your "datasources.json" file like this:
`"storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "provider": "amazon",
    "region": "eu-central-1",
    "key": "...",
    "keyId": "..."
  }`
I don't know why the "region" field doesn't appear in "Properties" of Amazon provider in loopback docs:
https://loopback.io/doc/en/lb2/Storage-component.html

I hope it helps you.

**Comment by jordymeow** [comment]
Thank you, indeed, that works perfectly :) I guess the documentation was a bit lacking but it all works fine.
