### ISSUE TITLE
Google Cloud Support

### ISSUE THREAD

**Issue by ferdigokdemir** [strongloop/loopback-component-storage#199]
Google Cloud Storage is supporting ?
https://github.com/pkgcloud/pkgcloud is supporting to google cloud.

**Comment by Overdrivr** [comment]
Yes it's supported, just create a datasource with the following fields:

```
"name": "bucket-name", // The name that will appear inside your cloud storage browser
"connector": "loopback-component-storage",
"provider": "google",
"keyFilename": "/path/to/keyfile.json", // Create a service account and give read, write, or admin role on storage (google cloud console -> IAM and admin -> service account -> create one) 
"projectId": "123...789" // Replace with your own, can be found in google cloud console -> storage -> parameters
```
See here for google-specific authentication for storage with [pkgcloud](https://github.com/pkgcloud/pkgcloud/blob/master/docs/providers/google.md#using-storage)

**Comment by Overdrivr** [comment]
@crandmck This issue has been closed because of inactivity, but it could be easily fixed by updating the documentation

**Comment by crandmck** [comment]
Thanks for noticing, @Overdrivr .  This wasn't on my radar since it was not tagged with `doc` label, nor mentioned me, etc.

Anyway, I'll add this to the docs, but since I haven't actually it myself, can you please confirm that this does work using the data source config noted above ^ ... ?

**Comment by Overdrivr** [comment]
Thanks @crandmck for your reply, here is the config template I'm using:
```
"storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "provider": "google",
    "keyFilename": "./path/to/keyfile.json",
    "projectId": "<gcloud project id>",
    "nameConflict": "makeUnique"
  }
```

It's basically the [config data that pkgcloud needs](https://github.com/pkgcloud/pkgcloud/blob/master/docs/providers/google.md#using-storage).

I can't remember where the `nameConflict` field comes from, it's optionnal if you don't need unique names.
