### ISSUE TITLE
Controlling filename used for upload based on user info

### ISSUE THREAD

**Issue by nowherenearithaca** [strongloop/loopback-component-storage#20]
I was able to tweak this so that I could put things in a place specific to an authenticated user (via passport social login with ensureloggedin), modifying the storage-handler.js file.  Not sure if it's the best way, though, so adding this note to compare when you get around to adding something like this.

Primarily, at the top of exports.upload, check to see if req.user.getNewFilenameForUser exists (and req.user, of course), and if so then call that to get the filename to for the upload (strategy for creating new filenames arbitrary - I'm using uuid's and userid).  This function can be added to user via the suggestions in loopback 2.0 docs by creating a user.js file (http://docs.strongloop.com/display/LB/Migrating+existing+apps+to+version+2.0, the section on "Models").  The resulting filename is then used further below in the provider.upload(...) call.  When the file is finished uploading, the method user.fileWasUploaded(info) is called (if it exists) so that the User model can save info to db on the upload.

There's other grunt stuff to do on managing uploads, but this is a first step - curious to see what you end up doing.

**Comment by raymondfeng** [comment]
@mymainmanbrown Sorry for the delay. Here is the simple way to submit a PR.

1. Folk the github repo into your own account
2. Clone/check out the repo from your account
3. Make changes, commit them, and push back to your repo
4. Following instructions at https://help.github.com/articles/creating-a-pull-request/ to submit a PR with your changes

**Comment by seriousben** [comment]
@raymondfeng Just created a PR addressing this.

**Comment by neyric** [comment]
Did the same here : https://github.com/strongloop/loopback-component-storage/pull/42

**Comment by seriousben** [comment]
I merged @neyric PR #42 within mine #41 to get the best of both worlds.

**Comment by seriousben** [comment]
Fixed by #41
