### ISSUE TITLE
Update pkgcloud dependency version to avoid NSP security vulnerability

### ISSUE THREAD

**Issue by mikewli** [strongloop/loopback-component-storage#200]
Hi,

I'm letting you know that your dependency, pkgcloud@1.4.0 uses request@2.40.0 which has another vulnerability listed in addition to the one aforementioned:
https://nodesecurity.io/advisories/309 (Remote Memory Exposure)

I'm currently ignoring https://nodesecurity.io/advisories/77, since I have a CI build system but that's obviously not ideal.

I've found an issue where they are discussing the NSP vulnerabilities for pkgcloud, would be great if you guys could chime in too and/or help resolve.
https://github.com/pkgcloud/pkgcloud/issues/506

Currently, as I write this post, pkgcloud 1.4.0 is the latest, so presumably you'd need to get them to update their dependency to solve this problem.

**Comment by TimPerry** [comment]
Also running into this.

**Comment by 3z3qu13l** [comment]
Hi,
2 more vulnerabilities are revealed in pkgcloud:
- https://nodesecurity.io/advisories/605 (loopback-component-storage@3.3.1 >   │pkgcloud@1.5.0 > gcloud@0.10.0 > protobufjs@3.8.2)
- https://nodesecurity.io/advisories/577 (loopback-component-storage@3.3.1 >   │ pkgcloud@1.5.0 > lodash@3.10.1)
