### ISSUE TITLE
Support for any s3 object storage

### ISSUE THREAD

**Issue by shenghu** [strongloop/loopback-component-storage#203]
Some object storage service provide S3 API in addition to its proprietary API, e.g. CleverSafe. If this component can provide a kind of 'S3' provider, it can be used w/ more object storage services. 

JClouds (https://jclouds.apache.org/reference/providers/) has similar functions. E.g. I can connect to CleverSafe w/ this setting,

jclouds.provider=s3
jclouds.endpoint={url}
jclouds.identity={keyId}
jclouds.credential={key}
jclouds.keystone.credential-type=tempAuthCredentials

It will be good to see this is supported. Or please let me know if it's already there.

**Comment by ssshah5** [comment]
I have a similar use case where I am trying to use loopback with CleverSafe. Is this possible? Would appreciate any pointers.

**Comment by haoxy0** [comment]
Co-worked with a colleague Shrenik, tried out CleverSafe works with Amazon provider. I'd like to know is it formal supported by  loopback-component-storage?

I use it in this way:
 "storage:amazon": {
    "name": "storage:amazon",
    "connector": "**loopback-component-storage**",
    "provider": "**amazon**",
    "key": key,
    "keyId": keyId,
    **"endpoint":**  urlofCleverSafe,
    **"forcePathBucket": true**
  },
