### ISSUE TITLE
Document how to set filenames server-side

### ISSUE THREAD

**Issue by will-fgmnt** [strongloop/loopback-component-storage#208]
Can we **please** get some documentation on the correct way of generating filenames server-side? The default seems to be to simply write the filename to the underlying storage as-is which seems like a pretty dangerous default as a malicious user may construct a path which overwrites another users file. I realise there is the `makeUnique` option but I want more control over the final path.

**Comment by jackrvaughan** [comment]
In a boot file I've run this code to change the file name:

`'use strict';

module.exports = function(app) {
  var modelNames = Object.keys(app.models);

  app.dataSources.<<MODEL>>.getFilename = function (origFilename, req, res) {
    //code for setting new file name
    return <<NEW FILE NAME>>
  }
};`
