### ISSUE TITLE
Integration with Object storage service in bluemix

### ISSUE THREAD

**Issue by JyotiRani** [strongloop/loopback-component-storage#211]
We have a requirement to store attachments in Object storage (service in bluemix OpenStack).  I referred to https://loopback.io/doc/en/lb2/Storage-component.html loopback documentation for storage component which also supports Openstack provider with following configuration:

{
 provider: 'openstack',
 username: '...',
 password: '...',
 authUrl: 'https://your-identity-service'
}

I created service instance of Object storage and generated the credentials and based on that defined datasource as below:

Object storage credentials:

{
  "auth_url": "https://identity.open.softlayer.com",
  "project": "object_storage_fdc3bcd8_ff01_4c67_a1c8_c99773dbfdca",
  "projectId": "f0b5ffd7393d46e991f592a042ebde3c",
  "region": "dallas",
  "userId": "b109b5c68ace4e45acab823add8f56ae",
  "username": "admin_******************",
  "password": "",
  "domainId": "7dce3f4358ea4524ac84c7a1aaf00c35",
  "domainName": "861075",
  "role": "admin"
}

datasource configuration

  "attachments": {
    "username": "admin_**********",
    "password": "",
    "name": "attachments",
    "connector": "loopback-component-storage",
    "provider": "openstack",
    "authUrl": "https://identity.open.softlayer.com"
  }

But this doesn't seem to work, fails with 401 unauthorized error as below:

Error:

{"error":{"statusCode":401,"name":"Error","message":"Error (401): Unauthorized","failCode":"Unauthorized","href":"https://identity.open.softlayer.com/v2.0/tokens","method":"POST","headers":{"date":"Fri, 28 Jul 2017 08:37:38 GMT","server":"Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_wsgi/3.4 Python/2.7.5","vary":"X-Auth-Token","x-openstack-request-id":"req-80e05d6e-9fbe-48ce-84e7-c6b472ea5d0e","www-authenticate":"Keystone uri=\"https://identity.open.softlayer.com\"","content-length":"114","cache-control":"no-cache, no-store, must-revalidate","pragma":"no-cache","expires":"0","content-security-policy":"default-src 'self'","x-content-type-options":"nosniff","x-xss-protection":"0","strict-transport-security":"max-age=31536000","keep-alive":"timeout=5, max=89","connection":"Keep-Alive","content-type":"application/json"},"result":{"error":{"message":"The request you have made requires authentication.","code":401,"title":"Unauthorized"}},"stack":"Error: Error (401): Unauthorized\n    at Object.exports.handle (C:\\HCL\\loopback examples\\loopback-example-storage\\test\\fileupload\\node_modules\\errs\\lib\\errs.js:203:19)\n    at C:\\HCL\\loopback examples\\loopback-example-storage\\test\\fileupload\\node_modules\\pkgcloud\\lib\\pkgcloud\\openstack\\client.js:214:23\n    at C:\\HCL\\loopback examples\\loopback-example-storage\\test\\fileupload\\node_modules\\pkgcloud\\lib\\pkgcloud\\openstack\\client.js:162:14\n    at Request._callback (C:\\HCL\\loopback examples\\loopback-example-storage\\test\\fileupload\\node_modules\\pkgcloud\\lib\\pkgcloud\\openstack\\context\\identity.js:160:14)\n    at Request.self.callback (C:\\HCL\\loopback examples\\loopback-example-storage\\test\\fileupload\\node_modules\\pkgcloud\\node_modules\\request\\request.js:123:22)\n    at emitTwo (events.js:106:13)\n    at Request.emit (events.js:191:7)\n    at Request.<anonymous> (C:\\HCL\\loopback examples\\loopback-example-storage\\test\\fileupload\\node_modules\\pkgcloud\\node_modules\\request\\request.js:1047:14)\n    at emitOne (events.js:101:20)\n    at Request.emit (events.js:188:7)\n    at IncomingMessage.<anonymous> (C:\\HCL\\loopback examples\\loopback-example-storage\\test\\fileupload\\node_modules\\pkgcloud\\node_modules\\request\\request.js:998:12)\n    at emitNone (events.js:91:20)\n    at IncomingMessage.emit (events.js:185:7)\n    at endReadableNT (_stream_readable.js:974:12)\n    at _combinedTickCallback (internal/process/next_tick.js:74:11)"}}

What else is missing in the above configuration? Do you have an example of sample datasource configuration for openstack?

**Comment by b-admike** [comment]
Hi @JyotiRani I was able to create an Object Storage service in Bluemix and use it with my LB app without an issue. I was able to use the example app provided [here](https://github.com/strongloop/loopback-example-storage). Please make sure to [use this fix](https://github.com/strongloop/loopback-example-storage/pull/17) if you're using the `example-3.0` app. Here is what my datasource config looks like:
```
  "storage2": {
    "username": "admin_*******************",
    "password": "",
    "name": "storage2",
    "authUrl": "https://identity.open.softlayer.com",
    "tenantId": "",
    "domainId": "d6e0561b1c084e4190087227c861451d",
    "region": "dallas",
    "connector": "loopback-component-storage",
    "provider": "openstack",
    "useServiceCatalog": true,
    "useInternal": false,
    "keystoneAuthVersion": "v3"
  }
```

**Comment by JyotiRani** [comment]
Thanks for your inputs, it works for me now. I think documentation need to be updated on how we connect to Openstack with those additional params included in the sample configuration.
