### ISSUE TITLE
"TypeError: Cannot read property 'statusCode' of undefined"

### ISSUE THREAD

**Issue by lchenay** [strongloop/loopback-component-storage#22]
The given error "TypeError: Cannot read property 'statusCode' of undefined" appear only when uploading a file bigger than 4mo using a callback on uploadStream.

```
var s3 = new StorageService({
  provider: 'amazon',
  key: providers.amazon.key,
  keyId: providers.amazon.keyId
});

var fs = require('fs');
var stream = s3.uploadStream('uniq_container_name', 'file_bigger_than_4mo', function() {
    console.log('upload finish')
});
fs.createReadStream('/home/user/pictures/file_bigger_than_4mo.jpg').pipe(stream);

```

The callback is needed because stream.on('finish') is not triggered with amazon adapter.

**Comment by richardpringle** [comment]
Hey @lchenay, I'm just trying to deal with all these really old issues. Do you know if this is still an issue? 

Thank you!

**Comment by richardpringle** [comment]
@lchenay, I am closing this issue. Please re-open if you are still running into problems.
