### ISSUE TITLE
Remote Memory Exposure + Regular Expression Denial of Service  

### ISSUE THREAD

**Issue by hckhanh** [strongloop/loopback-component-storage#225]
I receive the NSP warning about security of two packages in this module

https://nodesecurity.io/advisories/309
https://nodesecurity.io/advisories/77

**Comment by matteo-harpoon** [comment]
Same thing here!

![Uploading Screen Shot 2017-09-19 at 12.25.36.png…]()

**Comment by cristtopher** [comment]
It's the same with me!
<img width="893" alt="cristtopher quintana t 2017-09-21 at 11 07 56" src="https://user-images.githubusercontent.com/1254710/30700173-3310f446-9ebd-11e7-8d56-218f3a19719f.png">
