### ISSUE TITLE
No debug strings available

### ISSUE THREAD

**Issue by Overdrivr** [strongloop/loopback-component-storage#227]
Are there any plans to add [debug strings](https://loopback.io/doc/en/lb2/Setting-debug-strings.html) to this component ?

**Comment by raymondfeng** [comment]
@Overdrivr Would you please contribute a PR?

**Comment by Overdrivr** [comment]
@raymondfeng Ok I will, I'll try to get it done this week

**Comment by Overdrivr** [comment]
This ticket is in process of implementation. I'm waiting for a first feedback (modifications are a no-brainer but some feedback would still be useful)

**Comment by Overdrivr** [comment]
MR is on its way, chill stale bot.
