### ISSUE TITLE
finish event on stream upload with adapter amazon is not triggered.

### ISSUE THREAD

**Issue by lchenay** [strongloop/loopback-component-storage#23]
```
var s3 = new StorageService({
  provider: 'amazon',
  key: providers.amazon.key,
  keyId: providers.amazon.keyId
});

var fs = require('fs');
var stream = s3.uploadStream('uniq_container_name', 'file.jpg');
fs.createReadStream('/home/user/pictures/file.jpg').pipe(stream);

stream.on('finish', function() {
    console.log('upload finish');
});
```

**Comment by technicallyfeasible** [comment]
You have to use the "success" event since this is triggered by pkgcloud (used internally by loopback-component-storage).
The real problem is that the loopback storage does not trigger that event so at the moment there is no provider-independent way to listen for the upload being finished.

**Comment by richardpringle** [comment]
Hey @lchenay and @technicallyfeasible, do you guys know if [the above commit](https://github.com/strongloop/loopback-component-storage/commit/db1b449affd34b9ae0daf43b7ff6f8179e0b7ff5) solved the issue? If so, I can close it and move on to making other fixes.

Thanks in advance

**Comment by richardpringle** [comment]
Closing the issue for now. Please re-open if it is still relevant.

**Comment by thiagomorato** [comment]
@richardpringle I think the issue still present, yesterday I tried using `finish` event and it was not working, I'm using `success` but I'm wondering what is the event for errors then?
