### ISSUE TITLE
How can I read text-only fields from the multi-part data?

### ISSUE THREAD

**Issue by TrevorPage** [strongloop/loopback-component-storage#233]
I need to have an endpoint which accepts multipart data where some parts are images and some parts are text-only metadata fields. Prior to attempting to use loopback-component-storage, I was using multer (`app.middleware('parse', multer().any());`) to allow me to access the text fields and files.

I can get loopback-component-storage to upload successfully to AWS, but only if I disable the use of multer by commenting out the `app.middleware('parse', multer().any());`. (Not doing so results in a hang for a long time, before an exception.) I expect this is because multer is consuming the files out of the raw HTTP request stream, screwing things up for loopback-component-storage.

So, how can I read those text-only fields from the multipart request while using this component to perform an upload please?

**Comment by TrevorPage** [comment]
Ah, I see now: They are provided in the `fields` property in the callback object from upload().

**Comment by rslhdyt** [comment]
Thanks @TrevorPage you save my time, I didn't realize that.

**Comment by TrevorPage** [comment]
@rslhdyt really glad that was useful :)

**Comment by pbalan** [comment]
Hi @TrevorPage , am also stuck with this. Could you please share your solution?

My problem is the following. I am trying to post the file as buffer as the original request is already parsing the json fields data.

What I am doing is the following, I send data for blog post with json and image. After json data consumed to generate the post, I want to save the file using `storage-component`. So I use afterremote hook to create another request using superagent and post the data to `/api/containers/blog-media/upload`.

At this point my socket hangs and request dies. :(

**Comment by pbalan** [comment]
@TrevorPage, just bumped into your [gist solution](https://gist.github.com/TrevorPage/eeed5022e03978d9d003898ffe00f7db). However, in my case it seems will not work. Did you happen to find to find out the solution for something like what I am trying to achieve?
