### ISSUE TITLE
Where is downloaded file located?

### ISSUE THREAD

**Issue by daffylumampao** [strongloop/loopback-component-storage#234]
Hi,

Just a question, In localhost/explorer, I used http://localhost:3000/api/attachments/{container}/download/{filename.json} and it returns a 200 success code but I can't seem to locate where the downloaded file is found. Where can I locate the file?

**Comment by daffylumampao** [comment]
@bajtos, may I ask how to make the response body a download link instead of just a printed version in the response body?

**Comment by daffylumampao** [comment]
@raymondfeng may I ask how to make the response body a download link instead of just a printed version in the response body?

**Comment by bajtos** [comment]
@daffylumampao This depends on how [Swagger UI](https://github.com/swagger-api/swagger-ui) handles file downloads. I am afraid I don't have bandwidth to investigate that myself, could you perhaps ask in there GitHub repo? The important bit is that LoopBack is using an older 2.x version of Swagger UI, not their latest 3.x.
