### ISSUE TITLE
How to create a custom remote method for downloading a file ?

### ISSUE THREAD

**Issue by JheelVala** [strongloop/loopback-component-storage#235]
My pdf files are uploaded to containers. 
I want to create custom api to download a file . Not able to download a file using container api i.e /containers/{container}/download/{file}
Any pointers would be helpful.

**Comment by jkunwar** [comment]
@JheelVala did you find any solution to this. I am also stuck in same problem.

**Comment by JheelVala** [comment]
@jkunwar - I haven't created remote method instead use same URL , and open file by using blob.

**Comment by arnaud-git** [comment]
Hello there, I found out that the documentation is wrong concerning a call to download directly from any remote method, it says you have to call it like this: 

![image](https://user-images.githubusercontent.com/12065908/37919177-7841efa4-3123-11e8-85b4-0a07ca538147.png)

But the function actually needs the request argument, if you follow the doc you'll get an error looking like: "res.type is not a function"

You should call your function like that : 
download(containerId, fileName, req, res, cb)

**Comment by hacksparrow** [comment]
@JheelVala so is your problem resolved? The full request path should be `/api/containers/{container}/download/{file}`, as you might have realized.

@jkunwar is there a reason why you want to create a custom method for downloading files? The regular method coupled with the Model file can almost do anything you want.

**Comment by jkunwar** [comment]
@JheelVala it did solved my problem. Thanks :)

**Comment by jkunwar** [comment]
@hacksparrow i have to do some check before download like authorization and other so i was trying to create remote method. But i used  "**beforeRemote**" hook to obtain what i wanted :). Thanks to strongloop comunity

**Comment by hacksparrow** [comment]
@jkunwar thanks for the confirmation 👍🏻
