### ISSUE TITLE
Cannot call method 'forEach' of undefined

### ISSUE THREAD

**Issue by slegouffe** [strongloop/loopback-component-storage#24]
Hi ! 
When I call api/storages/:containers/files where ":containers" is a folder that doesn't exists, server crash with this error :
> node_modules/loopback-component-storage/lib/providers/filesystem/index.js:204
>    entries.forEach(function (f) {
>            ^
> TypeError: Cannot call method 'forEach' of undefined

Enjoy ;-)

**Comment by richardpringle** [comment]
@slegouffe, thanks for pointing this out! You know if this is still an issue?
