### ISSUE TITLE
Rename file from before remote method using context

### ISSUE THREAD

**Issue by akvaliya** [strongloop/loopback-component-storage#240]
I want to rename file from before remote hook using context.

```
 container.beforeRemote('upload', function (context, res, next) {
      /////rename file
}
```

Can anyone tell me how can i access files from this?

**Comment by wheyerstrass** [comment]
Here is a workaround:
```javascript
module.exports = function(Storage) {

  Storage.afterRemote('upload', function(ctx, data, next) {
    const newName = ctx.req.query.name;
    const {container, name} = data.result.files.file[0];

    // file wants to be renamed
    if (newName) {

      // create new name with old ext
      let ext = name.split('.').slice(-1).pop();
      let newFullName = `${newName}.${ext}`;

      // pipe old file as new one with new name
      let dlStream = Storage.downloadStream(container, name);
      let ulStream = Storage.uploadStream(container, newFullName);
      dlStream.pipe(ulStream);
      ulStream.on('finish', () => {
        Storage.removeFile(container, name, (err) => {
          next();
        });
      });
    } else next();
  });
};
```
I pass a query parameter to the request to signal a different name. Then I pipe the download stream to the upload stream with the new name and delete the old one.

**Comment by akvaliya** [comment]
@wheyerstrass I need to rename file before upload. Because if more then one users uploads files with same name then it will replace files. Renaming after upload is useless.

**Comment by wheyerstrass** [comment]
@akvaliya Ok you have different conditions than I do. I dumped the whole `ctx` object into log and did not find a way to rename it.  
If you just need the files to be unique then you can use [set the option](https://loopback.io/doc/en/lb3/Storage-component.html#automatic-unique-filenames).

**Comment by hacksparrow** [comment]
@akvaliya you can use the `getFilename` option to rename files before they reach the destination - https://loopback.io/doc/en/lb3/Storage-component.html#renaming-files.

**Comment by akvaliya** [comment]
@hacksparrow Your suggestion is for renaming all files before upload. Not for specific remote method.

**Comment by hacksparrow** [comment]
@akvaliya can you share more details about your usecase (with an example)? `getFilename` has information about the uploading file; and access to the request and the response objects. It is pretty flexible and can conditionally either rename or not.

**Comment by dhmlau** [comment]
@akvaliya , any updates?

**Comment by akvaliya** [comment]
Nope. Still can't access/change file names from beforeRemote method.

**Comment by francescoderosa** [comment]
You can't access/change file names from beforeRemote method.
You should operate in remote method setting getFilename function as property of upload method, for example:
```
let fileName= `${contextVar}_${uuid.v4()}`;
                var options = {
                    container : `${bucket}/${prefix}`,
                    getFilename : function(file, req, res) {
                        let completeFileName = attachmentName + path.extname(file.name);
                        return completeFileName;
                    }.bind(attachmentName)
                };
```
Than you can call upload method:
```
Container.upload(req, res, options, (err, result) => {}
```

**Comment by darurats** [comment]
Is it possible if you want get the files in beforeRemote Upload?

**Comment by imxerex** [comment]
just add nameConfilict makeUnique to datasources.json in loopback project
`"storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "provider": "filesystem",
    "root": "./file/storage",
    "nameConflict":"makeUnique"
  }`
