### ISSUE TITLE
Documentation looks wrong about download method

### ISSUE THREAD

**Issue by arnaud-git** [strongloop/loopback-component-storage#241]
Hello, I've been struggling for a while about calling the download method directly from another remote method and I've figured out why. The documentation states that we have to call it with : 

![image](https://user-images.githubusercontent.com/12065908/37919328-da0e9bba-3123-11e8-9bdf-fa1ed82b7268.png)

However, if you don't pass it the req object, it won't work as the cb will be interpreted as the response... I'm not sure it is the right place to report this issue about doc, and would be glad to raise the issue at the correct place if you know it :)

Thanks anyway, keep it up with the great work !

**Comment by hacksparrow** [comment]
@arnaud-git thanks for reporting, it has been fixed now - http://loopback.io/doc/en/lb3/Storage-component.html.
