### ISSUE TITLE
Content-Length not returned in the response (unless Range header is set)

### ISSUE THREAD

**Issue by gizmhail** [strongloop/loopback-component-storage#243]
When downloading a file with this component in Loopback, the headers do not always contain the Content-Length.

The problem is in the download exported function, in lib/storage-handler.js.

When there is no range, the function simply call the internal download function:
```
  if (!range) {
    return download(params);
  }
```

I think that instead, it should first fetch the file information, and set the Content-Length header. For instance : 
```
  if (!range) {
    provider.getFile(params.container, params.remote, function(err, stats) {
        if (err) {
            return cb(processError(err, params.remote));
        }
        res.set('Content-Length', stats.size);
        download(params);
    });
    return;
  }
```

I'm not very used to nodejs nor Loopback team contributing policy, but if needed, I could prepare a pull request.

**Comment by Djinne** [comment]
I had a similar problem, See if my solution using requestJS helps, so piping solved my problem. 
https://github.com/strongloop/loopback-component-storage/issues/226
