### ISSUE TITLE
How Can I Get the File Content Before Upload?

### ISSUE THREAD

**Issue by Miruako** [strongloop/loopback-component-storage#245]
Through, I found this component can handle file name conflict by using uuid, but we have a requirement that need get the file's md5 as its file name. I have tried to get the file content before upload bu failed. 
So my question is: is there a way to get file content before upload so that can calculate the md5 and then write into the file system?

**Comment by hacksparrow** [comment]
@Miruako we can't get the file content before they are uploaded. Our implementation writes the file content in chunks as they arrive.

Imagine someone uploading a 10 GB file and we wait to read the content, while storing the uploading content in memory! 

You can rename the files inside an `upload` [`afterRemote`](https://loopback.io/doc/en/lb3/Remote-hooks.html) hook. By that time, you can read the file contents from disk. Eg:

```
  MyModel.afterRemote('upload', function(ctx, data, next) {
    const files = ctx.result.result.files;
    // Loop through the files and rename them
    // and then call next()
    next()
  });
