### ISSUE TITLE
Support for IBM Cloud Object Storage (COS)

### ISSUE THREAD

**Issue by srova** [strongloop/loopback-component-storage#253]
Hello, is there any plan to integrate this component with the IBM Cloud Object Storage (https://developer.ibm.com/recipes/tutorials/cloud-object-storage-s3-api-intro/) in the mid term?
The APIs seem to be quite similar to AWS S3.

Best regards

**Comment by dhmlau** [comment]
I think `loopback-component-storage` works with IBM Cloud Object Storage.  Someone had tried it before: https://github.com/strongloop/loopback-component-storage/issues/237.

cc @b-admike

**Comment by srova** [comment]
Made it working, the issue was not related to loopback-component-storage, but to pkgcloud library.
Here is the pull request, for anyone interested:
https://github.com/pkgcloud/pkgcloud/pull/625

**Comment by dhmlau** [comment]
@srova, thanks for the info.  Is this issue good to close?  Thanks.

**Comment by srova** [comment]
@dhmlau Yes, I confirm the issue can be closed
