### ISSUE TITLE
Doc is still referencing a callback arg for downloadStream

### ISSUE THREAD

**Issue by tkrugg** [strongloop/loopback-component-storage#254]
Hi. Great work on this project!

Doc is still referencing a callback arg for downloadStream
http://apidocs.loopback.io/loopback-component-storage/#storageservice-prototype-downloadstream

but it appears to have been removed 3 years ago, according to the [change log](https://github.com/strongloop/loopback-component-storage/blob/21d6b0d60ce674bcc7540aaa754eba9237d3627e/CHANGES.md#2015-03-02-version-131)

**Comment by dhmlau** [comment]
Thanks @tkrugg.  Would you like to submit a PR to update the apidocs?  
Here is where it's coming from: 
https://github.com/strongloop/loopback-component-storage/blob/master/lib/storage-service.js#L154-L176
