### ISSUE TITLE
Update storage example to 2.x layout

### ISSUE THREAD

**Issue by superkhau** [strongloop/loopback-component-storage#26]
- migrate `app.js` to a new repo named `loopback-example-storage`
- update to 2.x if necessary

**Comment by superkhau** [comment]
Do this example as a learning exercise in preparation for strongloop/loopback-component-storage#37

Connected to strongloop/loopback-component-storage#37

**Comment by raymondfeng** [comment]
The 2.0 example is already available: https://github.com/strongloop/loopback-component-storage/tree/master/example-2.0

**Comment by superkhau** [comment]
@raymondfeng I see the source, but it doesn't explain how to use it well. I think local storage works well. There are some other provider files that have no explanations, etc. I would like to see something like a faq repo (might rename to loopback-faq-file-storage later) with:

- Short overview of what is involved (ie. containers/files, datasource, container model, providers)
- configurations
- How to do a local file save
- How to do a third party file save (ie. using a cloud provider)
- How does storage work with loopback-explorer

At the moment the docs tell me "what", but there aren't many hows. Also that example doesn't seem to work with AWS (I put in the AWS key/secret and it doesn't save there, in addition I don't know where to set the bucket to save to, etc).

Anyways, I feel there are too many holes to move forward so I thought doing some simple examples will bring me up to speed. Thoughts?

**Comment by raymondfeng** [comment]
@superkhau I agree with your assessment. The idea is to refactor this example to its own repo and start to enhance it for the full functionality.

**Comment by superkhau** [comment]
@raymondfeng I see what you mean now. I will copy/paste the initial code from the connector here as a starting point.
