### ISSUE TITLE
Can not download

### ISSUE THREAD

**Issue by itgelo** [strongloop/loopback-component-storage#266]
I can't download, all api upload and everything else goes well except downloading
api/Containers/attachment/download/ff03b565-64eb-4fb8-b73e-763dc3dedcf4.jpg

![image](https://user-images.githubusercontent.com/15007559/53693011-06e7fb80-3dcc-11e9-9306-c595c695b5f1.png)

**Comment by leofuturer** [comment]
When I used this API, it did not report any error,  but just responded with the file content instead of downloading the file, kind of confusing.
