### ISSUE TITLE
pkgcloud dependency : updates

### ISSUE THREAD

**Issue by rachedanis** [strongloop/loopback-component-storage#269]
Hello, I'm having some troubles with grpc used in the pkgcloud dependency.
I've found that they're working on some improvement including removing that dependency in
[#651](https://github.com/pkgcloud/pkgcloud/pull/651).
It's mentionated that they will deliver these improvements in 2.x, so please consider supporting the 2.x when the PR will be merged.

**Comment by VerrNum** [comment]
Hi,
Same issue here like @rachedanis 

Thanks

**Comment by rachedanis** [comment]
FYI the https://github.com/pkgcloud/pkgcloud/pull/651 is merged, please consider supporting the 2.x, thanks.

**Comment by rachedanis** [comment]
Hello, the PR https://github.com/pkgcloud/pkgcloud/pull/651 was merged. There is another PR for the release : https://github.com/pkgcloud/pkgcloud/pull/656

**Comment by dhmlau** [comment]
https://github.com/strongloop/loopback-component-storage/pull/271 has merged. Closing this issue as resolved.  @rachedanis, thanks again for your contribution!
