### ISSUE TITLE
Upload method never calls the callback function

### ISSUE THREAD

**Issue by diegoazh** [strongloop/loopback-component-storage#273]
# Description/Steps to reproduce
I have an issue with storage component, I debug it and I realized that when `storage-handler.js` (line 217) call `writer.end();` the request never end. It never call a callback function `cb(null, {files: files, fields: fields});` to end the request and I don't know why this is happening. I can't find the bug and I'm not sure if this bug is happening in pkgcloud or formidable or in my own code.
An interesting point is that the file is successfuly uploaded to the storage bucket but the request never ends.
I created a small repository with my code for testing porpuses: `https://github.com/diegoazh/lb4-storage-test.git`.
I hope that any one of you can help me with this bug because this upload is an important feature of my application.
Thank you and regards.

1. Create a bucket in google cloud storage
2. Copy the secret.json key to the root folther of the project
3. Clone this repository: `https://github.com/diegoazh/lb4-storage-test.git`
4. Modify the storage-gc.datasource.json with the correct `projectId`
5. run `yarn && yarn start`
6. Go to `http://localhost:3000/spa`, that contains the same uploader that I use in my application
7. Add some file to the uploader and upload it

Following this steps you realize that the request never ends; if you debug it with vscode adding some debug points to the line that I mentioned above you can see that when the handler calls `writer.end();` the flow of the request stops at this point and never calls a callback.

# Link to reproduction sandbox
Clone this repository: `https://github.com/diegoazh/lb4-storage-test.git`

# Expected result
Call callback and close the request flow.

# Additional information

linux x64 10.15.3

├─┬ UNMET DEPENDENCY @loopback/boot@1.2.10
│ ├── @loopback/context@1.17.1
│ ├── @loopback/core@1.7.3
│ ├── @loopback/repository@1.5.8
│ ├── @loopback/service-proxy@1.1.13
├─┬ UNMET DEPENDENCY @loopback/context@1.17.1
│ ├── @loopback/metadata@1.1.7
├─┬ UNMET DEPENDENCY @loopback/core@1.7.3
│ ├── @loopback/context@1.17.1
├─┬ UNMET DEPENDENCY @loopback/openapi-v3@1.5.1
│ ├── @loopback/context@1.17.1
│ ├── @loopback/openapi-v3-types@1.0.21
│ ├── @loopback/repository-json-schema@1.5.1
├─┬ UNMET DEPENDENCY @loopback/repository@1.5.8
│ ├── @loopback/context@1.17.1
│ ├── @loopback/core@1.7.3
│ └── loopback-datasource-juggler@4.7.1
├─┬ UNMET DEPENDENCY @loopback/rest@1.13.1
│ ├── @loopback/context@1.17.1
│ ├── @loopback/core@1.7.3
│ ├── @loopback/http-server@1.2.6
│ ├── @loopback/openapi-v3@1.5.1
│ ├── @loopback/openapi-v3-types@1.0.21
├─┬ UNMET DEPENDENCY @loopback/rest-explorer@1.1.25
│ ├── @loopback/context@1.17.1
│ ├── @loopback/core@1.7.3
│ ├── @loopback/rest@1.13.1
├─┬ UNMET DEPENDENCY @loopback/service-proxy@1.1.13
│ ├── @loopback/context@1.17.1
│ ├── @loopback/core@1.7.3
│ └── loopback-datasource-juggler@4.7.1
├── UNMET DEPENDENCY loopback-component-storage@^3.6.1
└── UNMET DEPENDENCY loopback-connector-firestore@^1.0.7
npm ERR! missing: @loopback/boot@1.2.10, required by test@1.0.0
npm ERR! missing: @loopback/context@1.17.1, required by test@1.0.0
npm ERR! missing: @loopback/core@1.7.3, required by test@1.0.0
npm ERR! missing: @loopback/openapi-v3@1.5.1, required by test@1.0.0
npm ERR! missing: @loopback/repository@1.5.8, required by test@1.0.0
npm ERR! missing: @loopback/rest@1.13.1, required by test@1.0.0
npm ERR! missing: @loopback/rest-explorer@1.1.25, required by test@1.0.0
npm ERR! missing: @loopback/service-proxy@1.1.13, required by test@1.0.0
npm ERR! missing: loopback-component-storage@^3.6.1, required by test@1.0.0
npm ERR! missing: loopback-connector-firestore@^1.0.7, required by test@1.0.0
npm ERR! missing: @loopback/context@1.17.1, required by @loopback/boot@1.2.10
npm ERR! missing: @loopback/core@1.7.3, required by @loopback/boot@1.2.10
npm ERR! missing: @loopback/repository@1.5.8, required by @loopback/boot@1.2.10
npm ERR! missing: @loopback/service-proxy@1.1.13, required by @loopback/boot@1.2.10
npm ERR! missing: @types/debug@4.1.4, required by @loopback/boot@1.2.10
npm ERR! missing: @types/glob@7.1.1, required by @loopback/boot@1.2.10
npm ERR! missing: debug@4.1.1, required by @loopback/boot@1.2.10
npm ERR! missing: glob@7.1.4, required by @loopback/boot@1.2.10
npm ERR! missing: @types/events@3.0.0, required by @types/glob@7.1.1
npm ERR! missing: @types/node@12.0.4, required by @types/glob@7.1.1
npm ERR! missing: @types/minimatch@3.0.3, required by @types/glob@7.1.1
npm ERR! missing: ms@2.1.1, required by debug@4.1.1
npm ERR! missing: fs.realpath@1.0.0, required by glob@7.1.4
npm ERR! missing: inflight@1.0.6, required by glob@7.1.4
npm ERR! missing: inherits@2.0.3, required by glob@7.1.4
npm ERR! missing: minimatch@3.0.4, required by glob@7.1.4
npm ERR! missing: once@1.4.0, required by glob@7.1.4
npm ERR! missing: path-is-absolute@1.0.1, required by glob@7.1.4
npm ERR! missing: once@1.4.0, required by inflight@1.0.6
npm ERR! missing: wrappy@1.0.2, required by inflight@1.0.6
npm ERR! missing: brace-expansion@1.1.11, required by minimatch@3.0.4
npm ERR! missing: balanced-match@1.0.0, required by brace-expansion@1.1.11
npm ERR! missing: concat-map@0.0.1, required by brace-expansion@1.1.11
npm ERR! missing: wrappy@1.0.2, required by once@1.4.0
npm ERR! missing: @loopback/metadata@1.1.7, required by @loopback/context@1.17.1
npm ERR! missing: debug@4.1.1, required by @loopback/context@1.17.1
npm ERR! missing: p-event@4.1.0, required by @loopback/context@1.17.1
npm ERR! missing: uuid@3.3.2, required by @loopback/context@1.17.1
npm ERR! missing: debug@4.1.1, required by @loopback/metadata@1.1.7
npm ERR! missing: lodash@4.17.11, required by @loopback/metadata@1.1.7
npm ERR! missing: reflect-metadata@0.1.13, required by @loopback/metadata@1.1.7
npm ERR! missing: p-timeout@2.0.1, required by p-event@4.1.0
npm ERR! missing: p-finally@1.0.0, required by p-timeout@2.0.1
npm ERR! missing: @loopback/context@1.17.1, required by @loopback/core@1.7.3
npm ERR! missing: debug@4.1.1, required by @loopback/core@1.7.3
npm ERR! missing: @loopback/context@1.17.1, required by @loopback/openapi-v3@1.5.1
npm ERR! missing: @loopback/openapi-v3-types@1.0.21, required by @loopback/openapi-v3@1.5.1
npm ERR! missing: @loopback/repository-json-schema@1.5.1, required by @loopback/openapi-v3@1.5.1
npm ERR! missing: debug@4.1.1, required by @loopback/openapi-v3@1.5.1
npm ERR! missing: lodash@4.17.11, required by @loopback/openapi-v3@1.5.1
npm ERR! missing: openapi3-ts@1.3.0, required by @loopback/openapi-v3-types@1.0.21
npm ERR! missing: @loopback/context@1.17.1, required by @loopback/repository-json-schema@1.5.1
npm ERR! missing: @loopback/metadata@1.1.7, required by @loopback/repository-json-schema@1.5.1
npm ERR! missing: @loopback/repository@1.5.8, required by @loopback/repository-json-schema@1.5.1
npm ERR! missing: @types/json-schema@7.0.3, required by @loopback/repository-json-schema@1.5.1
npm ERR! missing: @loopback/context@1.17.1, required by @loopback/repository@1.5.8
npm ERR! missing: @loopback/core@1.7.3, required by @loopback/repository@1.5.8
npm ERR! missing: @types/debug@4.1.4, required by @loopback/repository@1.5.8
npm ERR! missing: debug@4.1.1, required by @loopback/repository@1.5.8
npm ERR! missing: lodash@4.17.11, required by @loopback/repository@1.5.8
npm ERR! missing: loopback-datasource-juggler@4.7.1, required by @loopback/repository@1.5.8
npm ERR! missing: async@2.6.2, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: debug@4.1.1, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: depd@2.0.0, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: inflection@1.12.0, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: lodash@4.17.11, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: loopback-connector@4.7.0, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: minimatch@3.0.4, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: qs@6.7.0, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: shortid@2.2.14, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: strong-globalize@4.1.3, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: traverse@0.6.6, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: uuid@3.3.2, required by loopback-datasource-juggler@4.7.1
npm ERR! missing: lodash@4.17.11, required by async@2.6.2
npm ERR! missing: async@2.6.2, required by loopback-connector@4.7.0
npm ERR! missing: bluebird@3.5.5, required by loopback-connector@4.7.0
npm ERR! missing: debug@3.2.6, required by loopback-connector@4.7.0
npm ERR! missing: msgpack5@4.2.1, required by loopback-connector@4.7.0
npm ERR! missing: strong-globalize@4.1.3, required by loopback-connector@4.7.0
npm ERR! missing: uuid@3.3.2, required by loopback-connector@4.7.0
npm ERR! missing: ms@2.1.1, required by debug@3.2.6
npm ERR! missing: bl@2.2.0, required by msgpack5@4.2.1
npm ERR! missing: inherits@2.0.3, required by msgpack5@4.2.1
npm ERR! missing: readable-stream@2.3.6, required by msgpack5@4.2.1
npm ERR! missing: safe-buffer@5.1.2, required by msgpack5@4.2.1
npm ERR! missing: readable-stream@2.3.6, required by bl@2.2.0
npm ERR! missing: safe-buffer@5.1.2, required by bl@2.2.0
npm ERR! missing: core-util-is@1.0.2, required by readable-stream@2.3.6
npm ERR! missing: inherits@2.0.3, required by readable-stream@2.3.6
npm ERR! missing: isarray@1.0.0, required by readable-stream@2.3.6
npm ERR! missing: process-nextick-args@2.0.0, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by readable-stream@2.3.6
npm ERR! missing: string_decoder@1.1.1, required by readable-stream@2.3.6
npm ERR! missing: util-deprecate@1.0.2, required by readable-stream@2.3.6
npm ERR! missing: safe-buffer@5.1.2, required by string_decoder@1.1.1
npm ERR! missing: nanoid@2.0.3, required by shortid@2.2.14
npm ERR! missing: accept-language@3.0.18, required by strong-globalize@4.1.3
npm ERR! missing: debug@4.1.1, required by strong-globalize@4.1.3
npm ERR! missing: globalize@1.4.2, required by strong-globalize@4.1.3
npm ERR! missing: lodash@4.17.11, required by strong-globalize@4.1.3
npm ERR! missing: md5@2.2.1, required by strong-globalize@4.1.3
npm ERR! missing: mkdirp@0.5.1, required by strong-globalize@4.1.3
npm ERR! missing: os-locale@3.1.0, required by strong-globalize@4.1.3
npm ERR! missing: yamljs@0.3.0, required by strong-globalize@4.1.3
npm ERR! missing: bcp47@1.1.2, required by accept-language@3.0.18
npm ERR! missing: stable@0.1.8, required by accept-language@3.0.18
npm ERR! missing: cldrjs@0.5.1, required by globalize@1.4.2
npm ERR! missing: charenc@0.0.2, required by md5@2.2.1
npm ERR! missing: crypt@0.0.2, required by md5@2.2.1
npm ERR! missing: is-buffer@1.1.6, required by md5@2.2.1
npm ERR! missing: minimist@0.0.8, required by mkdirp@0.5.1
npm ERR! missing: execa@1.0.0, required by os-locale@3.1.0
npm ERR! missing: lcid@2.0.0, required by os-locale@3.1.0
npm ERR! missing: mem@4.3.0, required by os-locale@3.1.0
npm ERR! missing: cross-spawn@6.0.5, required by execa@1.0.0
npm ERR! missing: get-stream@4.1.0, required by execa@1.0.0
npm ERR! missing: is-stream@1.1.0, required by execa@1.0.0
npm ERR! missing: npm-run-path@2.0.2, required by execa@1.0.0
npm ERR! missing: p-finally@1.0.0, required by execa@1.0.0
npm ERR! missing: signal-exit@3.0.2, required by execa@1.0.0
npm ERR! missing: strip-eof@1.0.0, required by execa@1.0.0
npm ERR! missing: nice-try@1.0.5, required by cross-spawn@6.0.5
npm ERR! missing: path-key@2.0.1, required by cross-spawn@6.0.5
npm ERR! missing: semver@5.7.0, required by cross-spawn@6.0.5
npm ERR! missing: shebang-command@1.2.0, required by cross-spawn@6.0.5
npm ERR! missing: which@1.3.1, required by cross-spawn@6.0.5
npm ERR! missing: shebang-regex@1.0.0, required by shebang-command@1.2.0
npm ERR! missing: isexe@2.0.0, required by which@1.3.1
npm ERR! missing: pump@3.0.0, required by get-stream@4.1.0
npm ERR! missing: end-of-stream@1.4.1, required by pump@3.0.0
npm ERR! missing: once@1.4.0, required by pump@3.0.0
npm ERR! missing: once@1.4.0, required by end-of-stream@1.4.1
npm ERR! missing: path-key@2.0.1, required by npm-run-path@2.0.2
npm ERR! missing: invert-kv@2.0.0, required by lcid@2.0.0
npm ERR! missing: map-age-cleaner@0.1.3, required by mem@4.3.0
npm ERR! missing: mimic-fn@2.1.0, required by mem@4.3.0
npm ERR! missing: p-is-promise@2.1.0, required by mem@4.3.0
npm ERR! missing: p-defer@1.0.0, required by map-age-cleaner@0.1.3
npm ERR! missing: argparse@1.0.10, required by yamljs@0.3.0
npm ERR! missing: glob@7.1.4, required by yamljs@0.3.0
npm ERR! missing: @loopback/context@1.17.1, required by @loopback/rest@1.13.1
npm ERR! missing: @loopback/core@1.7.3, required by @loopback/rest@1.13.1
npm ERR! missing: @loopback/http-server@1.2.6, required by @loopback/rest@1.13.1
npm ERR! missing: @loopback/openapi-v3@1.5.1, required by @loopback/rest@1.13.1
npm ERR! missing: @loopback/openapi-v3-types@1.0.21, required by @loopback/rest@1.13.1
npm ERR! missing: @types/body-parser@1.17.0, required by @loopback/rest@1.13.1
npm ERR! missing: @types/cors@2.8.5, required by @loopback/rest@1.13.1
npm ERR! missing: @types/express@4.16.1, required by @loopback/rest@1.13.1
npm ERR! missing: @types/express-serve-static-core@4.16.6, required by @loopback/rest@1.13.1
npm ERR! missing: @types/http-errors@1.6.1, required by @loopback/rest@1.13.1
npm ERR! missing: @types/on-finished@2.3.1, required by @loopback/rest@1.13.1
npm ERR! missing: @types/serve-static@1.13.2, required by @loopback/rest@1.13.1
npm ERR! missing: @types/type-is@1.6.2, required by @loopback/rest@1.13.1
npm ERR! missing: ajv@6.10.0, required by @loopback/rest@1.13.1
npm ERR! missing: body-parser@1.19.0, required by @loopback/rest@1.13.1
npm ERR! missing: cors@2.8.5, required by @loopback/rest@1.13.1
npm ERR! missing: debug@4.1.1, required by @loopback/rest@1.13.1
npm ERR! missing: express@4.17.1, required by @loopback/rest@1.13.1
npm ERR! missing: http-errors@1.7.2, required by @loopback/rest@1.13.1
npm ERR! missing: js-yaml@3.13.1, required by @loopback/rest@1.13.1
npm ERR! missing: lodash@4.17.11, required by @loopback/rest@1.13.1
npm ERR! missing: on-finished@2.3.0, required by @loopback/rest@1.13.1
npm ERR! missing: openapi-schema-to-json-schema@2.2.0, required by @loopback/rest@1.13.1
npm ERR! missing: path-to-regexp@3.0.0, required by @loopback/rest@1.13.1
npm ERR! missing: qs@6.7.0, required by @loopback/rest@1.13.1
npm ERR! missing: strong-error-handler@3.2.0, required by @loopback/rest@1.13.1
npm ERR! missing: type-is@1.6.18, required by @loopback/rest@1.13.1
npm ERR! missing: validator@11.0.0, required by @loopback/rest@1.13.1
npm ERR! missing: p-event@4.1.0, required by @loopback/http-server@1.2.6
npm ERR! missing: @types/node@12.0.4, required by @types/body-parser@1.17.0
npm ERR! missing: @types/connect@3.4.32, required by @types/body-parser@1.17.0
npm ERR! missing: @types/node@12.0.4, required by @types/connect@3.4.32
npm ERR! missing: @types/express@4.16.1, required by @types/cors@2.8.5
npm ERR! missing: @types/body-parser@1.17.0, required by @types/express@4.16.1
npm ERR! missing: @types/express-serve-static-core@4.16.6, required by @types/express@4.16.1
npm ERR! missing: @types/serve-static@1.13.2, required by @types/express@4.16.1
npm ERR! missing: @types/node@12.0.4, required by @types/express-serve-static-core@4.16.6
npm ERR! missing: @types/range-parser@1.2.3, required by @types/express-serve-static-core@4.16.6
npm ERR! missing: @types/node@12.0.4, required by @types/on-finished@2.3.1
npm ERR! missing: @types/express-serve-static-core@4.16.6, required by @types/serve-static@1.13.2
npm ERR! missing: @types/mime@2.0.1, required by @types/serve-static@1.13.2
npm ERR! missing: @types/node@12.0.4, required by @types/type-is@1.6.2
npm ERR! missing: fast-deep-equal@2.0.1, required by ajv@6.10.0
npm ERR! missing: fast-json-stable-stringify@2.0.0, required by ajv@6.10.0
npm ERR! missing: json-schema-traverse@0.4.1, required by ajv@6.10.0
npm ERR! missing: uri-js@4.2.2, required by ajv@6.10.0
npm ERR! missing: punycode@2.1.1, required by uri-js@4.2.2
npm ERR! missing: debug@2.6.9, required by body-parser@1.19.0
npm ERR! missing: depd@1.1.2, required by body-parser@1.19.0
npm ERR! missing: bytes@3.1.0, required by body-parser@1.19.0
npm ERR! missing: content-type@1.0.4, required by body-parser@1.19.0
npm ERR! missing: http-errors@1.7.2, required by body-parser@1.19.0
npm ERR! missing: iconv-lite@0.4.24, required by body-parser@1.19.0
npm ERR! missing: on-finished@2.3.0, required by body-parser@1.19.0
npm ERR! missing: qs@6.7.0, required by body-parser@1.19.0
npm ERR! missing: raw-body@2.4.0, required by body-parser@1.19.0
npm ERR! missing: type-is@1.6.18, required by body-parser@1.19.0
npm ERR! missing: ms@2.0.0, required by debug@2.6.9
npm ERR! missing: safer-buffer@2.1.2, required by iconv-lite@0.4.24
npm ERR! missing: bytes@3.1.0, required by raw-body@2.4.0
npm ERR! missing: http-errors@1.7.2, required by raw-body@2.4.0
npm ERR! missing: iconv-lite@0.4.24, required by raw-body@2.4.0
npm ERR! missing: unpipe@1.0.0, required by raw-body@2.4.0
npm ERR! missing: object-assign@4.1.1, required by cors@2.8.5
npm ERR! missing: vary@1.1.2, required by cors@2.8.5
npm ERR! missing: accepts@1.3.7, required by express@4.17.1
npm ERR! missing: array-flatten@1.1.1, required by express@4.17.1
npm ERR! missing: body-parser@1.19.0, required by express@4.17.1
npm ERR! missing: content-disposition@0.5.3, required by express@4.17.1
npm ERR! missing: content-type@1.0.4, required by express@4.17.1
npm ERR! missing: cookie@0.4.0, required by express@4.17.1
npm ERR! missing: cookie-signature@1.0.6, required by express@4.17.1
npm ERR! missing: encodeurl@1.0.2, required by express@4.17.1
npm ERR! missing: escape-html@1.0.3, required by express@4.17.1
npm ERR! missing: etag@1.8.1, required by express@4.17.1
npm ERR! missing: debug@2.6.9, required by express@4.17.1
npm ERR! missing: depd@1.1.2, required by express@4.17.1
npm ERR! missing: path-to-regexp@0.1.7, required by express@4.17.1
npm ERR! missing: finalhandler@1.1.2, required by express@4.17.1
npm ERR! missing: fresh@0.5.2, required by express@4.17.1
npm ERR! missing: merge-descriptors@1.0.1, required by express@4.17.1
npm ERR! missing: methods@1.1.2, required by express@4.17.1
npm ERR! missing: on-finished@2.3.0, required by express@4.17.1
npm ERR! missing: parseurl@1.3.3, required by express@4.17.1
npm ERR! missing: proxy-addr@2.0.5, required by express@4.17.1
npm ERR! missing: qs@6.7.0, required by express@4.17.1
npm ERR! missing: range-parser@1.2.1, required by express@4.17.1
npm ERR! missing: safe-buffer@5.1.2, required by express@4.17.1
npm ERR! missing: send@0.17.1, required by express@4.17.1
npm ERR! missing: serve-static@1.14.1, required by express@4.17.1
npm ERR! missing: setprototypeof@1.1.1, required by express@4.17.1
npm ERR! missing: statuses@1.5.0, required by express@4.17.1
npm ERR! missing: type-is@1.6.18, required by express@4.17.1
npm ERR! missing: utils-merge@1.0.1, required by express@4.17.1
npm ERR! missing: vary@1.1.2, required by express@4.17.1
npm ERR! missing: mime-types@2.1.24, required by accepts@1.3.7
npm ERR! missing: negotiator@0.6.2, required by accepts@1.3.7
npm ERR! missing: safe-buffer@5.1.2, required by content-disposition@0.5.3
npm ERR! missing: ms@2.0.0, required by debug@2.6.9
npm ERR! missing: encodeurl@1.0.2, required by finalhandler@1.1.2
npm ERR! missing: escape-html@1.0.3, required by finalhandler@1.1.2
npm ERR! missing: debug@2.6.9, required by finalhandler@1.1.2
npm ERR! missing: on-finished@2.3.0, required by finalhandler@1.1.2
npm ERR! missing: parseurl@1.3.3, required by finalhandler@1.1.2
npm ERR! missing: statuses@1.5.0, required by finalhandler@1.1.2
npm ERR! missing: unpipe@1.0.0, required by finalhandler@1.1.2
npm ERR! missing: ms@2.0.0, required by debug@2.6.9
npm ERR! missing: forwarded@0.1.2, required by proxy-addr@2.0.5
npm ERR! missing: ipaddr.js@1.9.0, required by proxy-addr@2.0.5
npm ERR! missing: destroy@1.0.4, required by send@0.17.1
npm ERR! missing: encodeurl@1.0.2, required by send@0.17.1
npm ERR! missing: escape-html@1.0.3, required by send@0.17.1
npm ERR! missing: etag@1.8.1, required by send@0.17.1
npm ERR! missing: fresh@0.5.2, required by send@0.17.1
npm ERR! missing: http-errors@1.7.2, required by send@0.17.1
npm ERR! missing: mime@1.6.0, required by send@0.17.1
npm ERR! missing: ms@2.1.1, required by send@0.17.1
npm ERR! missing: on-finished@2.3.0, required by send@0.17.1
npm ERR! missing: range-parser@1.2.1, required by send@0.17.1
npm ERR! missing: debug@2.6.9, required by send@0.17.1
npm ERR! missing: depd@1.1.2, required by send@0.17.1
npm ERR! missing: statuses@1.5.0, required by send@0.17.1
npm ERR! missing: ms@2.0.0, required by debug@2.6.9
npm ERR! missing: encodeurl@1.0.2, required by serve-static@1.14.1
npm ERR! missing: escape-html@1.0.3, required by serve-static@1.14.1
npm ERR! missing: parseurl@1.3.3, required by serve-static@1.14.1
npm ERR! missing: send@0.17.1, required by serve-static@1.14.1
npm ERR! missing: depd@1.1.2, required by http-errors@1.7.2
npm ERR! missing: inherits@2.0.3, required by http-errors@1.7.2
npm ERR! missing: setprototypeof@1.1.1, required by http-errors@1.7.2
npm ERR! missing: statuses@1.5.0, required by http-errors@1.7.2
npm ERR! missing: toidentifier@1.0.0, required by http-errors@1.7.2
npm ERR! missing: argparse@1.0.10, required by js-yaml@3.13.1
npm ERR! missing: esprima@4.0.1, required by js-yaml@3.13.1
npm ERR! missing: sprintf-js@1.0.3, required by argparse@1.0.10
npm ERR! missing: ee-first@1.1.1, required by on-finished@2.3.0
npm ERR! missing: deep-equal@1.0.1, required by openapi-schema-to-json-schema@2.2.0
npm ERR! missing: @types/express@4.16.1, required by strong-error-handler@3.2.0
npm ERR! missing: accepts@1.3.7, required by strong-error-handler@3.2.0
npm ERR! missing: ejs@2.6.1, required by strong-error-handler@3.2.0
npm ERR! missing: http-status@1.3.2, required by strong-error-handler@3.2.0
npm ERR! missing: js2xmlparser@3.0.0, required by strong-error-handler@3.2.0
npm ERR! missing: debug@3.2.6, required by strong-error-handler@3.2.0
npm ERR! missing: strong-globalize@4.1.3, required by strong-error-handler@3.2.0
npm ERR! missing: xmlcreate@1.0.2, required by js2xmlparser@3.0.0
npm ERR! missing: ms@2.1.1, required by debug@3.2.6
npm ERR! missing: media-typer@0.3.0, required by type-is@1.6.18
npm ERR! missing: mime-types@2.1.24, required by type-is@1.6.18
npm ERR! missing: mime-db@1.40.0, required by mime-types@2.1.24
npm ERR! missing: @loopback/context@1.17.1, required by @loopback/rest-explorer@1.1.25
npm ERR! missing: @loopback/core@1.7.3, required by @loopback/rest-explorer@1.1.25
npm ERR! missing: @loopback/rest@1.13.1, required by @loopback/rest-explorer@1.1.25
npm ERR! missing: ejs@2.6.1, required by @loopback/rest-explorer@1.1.25
npm ERR! missing: swagger-ui-dist@3.22.2, required by @loopback/rest-explorer@1.1.25
npm ERR! missing: @loopback/context@1.17.1, required by @loopback/service-proxy@1.1.13
npm ERR! missing: @loopback/core@1.7.3, required by @loopback/service-proxy@1.1.13
npm ERR! missing: loopback-datasource-juggler@4.7.1, required by @loopback/service-proxy@1.1.13

**Comment by dhmlau** [comment]
@hacksparrow, could you please take a look? Thanks.

**Comment by diegoazh** [comment]
This issue has been solved in pkgcloud library with the last merge in master branch: [https://github.com/pkgcloud/pkgcloud/pull/666](https://github.com/pkgcloud/pkgcloud/pull/666), the fix it but they not changed the version of the package so that this fix is not yet in the npm package that you installed with the storage component. I not sure when they released this change but it solves this bug.

**Comment by diegoazh** [comment]
I created a new PR to fix this issue [#276](https://github.com/strongloop/loopback-component-storage/pull/276) with this simple change this issue is fixed, I test it in my app. Thank you.

**Comment by dhmlau** [comment]
@diegoazh , your PR #276 has merged. Thanks again for your contribution.
