### ISSUE TITLE
How can i hook to event fileBegin ?

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback-component-storage#28]
I want to custom my uploaded filename, so i want to hook to event fileBegin to change name of uploaded filename. So what can i do now ?

**Comment by vasumahesh1** [comment]
Still no answer? :( ... I am struggling on this issue...

**Comment by richardpringle** [comment]
Hey @bluestaralone  and @vasumahesh1, I believe that this can be achieved by using a `remoteHook` for instance:
```
Container.beforeRemote('upload', function(context, unused, next) {
    // Change the request parameters within the context here...
    next();
});
```
I'll get back to you about the details of what you need to change and make sure this is possible.

**Comment by richardpringle** [comment]
@bluestaralone @vasumahesh1, did my comment above help you out? If not, the best place to ask would be in one of the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

I am closing this for now as we are trying to maintain the issues sections on GitHub for bugs and feature requests.

If there is still a problem, open a new issue and mention me in a comment and I will see what I can do.

**Comment by ufukomer** [comment]
@richardpringle thanks
