### ISSUE TITLE
How can check file mine-type (extension) ?

### ISSUE THREAD

**Issue by bluestaralone** [strongloop/loopback-component-storage#29]
How can check file mine-type (extension) ?

**Comment by richardpringle** [comment]
@bluestaralone, sorry that no one has responded to your question!
For all questions, please post on one of the following:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We're using GitHub issues for features and bug requests only.
