### ISSUE TITLE
LoopBack 4 Confusing documentation 

### ISSUE THREAD

**Issue by ashkank83** [strongloop/loopback-component-storage#290]
Follwoing link in LB4 documentation suggest this component is usable in LB4
https://loopback.io/doc/en/lb4/Storage-connector.html

However the readme file of this component suggests otherwise. Would you please clarify if this can be used with LB4 or not? and if yes how can I use it?

I simply need to be able to upload and download files from local storage (on my server) using LB4.

**Comment by emonddr** [comment]
Our LoopBack 3 product is reaching EOL, and we are in the process of writing migration docs
https://loopback.io/doc/en/lb4/migration-overview.html . 

So this is why some bits and pieces of our docs are in a state of flux. Apologies for the confusion it caused you.

In LoopBack 4, you can try this new example which landed a few days ago:

https://github.com/strongloop/loopback-next/tree/master/examples/file-upload 


Just this morning, I asked the team to update it to also have download functionality.
It makes use of https://www.npmjs.com/package/multer .

:)

**Comment by ashkank83** [comment]
@emonddr Thanks a lot for quick response. I have looked into the file-upload example as well, however that seems to be covering only upload side. Where the loopback-component-storage suggests to be able to handle both uploading and getting files. 
I also found this answer on SO which seems to be suggesting using component storage with LB4:
https://stackoverflow.com/a/55213810/180260

Would you kindly let me know your professional opinion on the answer provided on SO? is thsi a recommended approach by LB team or not? ( I simply want to be able to upload files, store details in my database and then send them back to the web client to be displayed)

Thanks

**Comment by emonddr** [comment]
Here is the PR for the download side as well.

https://github.com/strongloop/loopback-next/pull/4861

**Comment by ashkank83** [comment]
Thanks. I followed the instructions from the stackoverflow answer (shared above) and have to say it's working like a charm! Will keep that implementation for now.

**Comment by emonddr** [comment]
ok. sounds good :)
