### ISSUE TITLE
Upload local file

### ISSUE THREAD

**Issue by cajoy** [strongloop/loopback-component-storage#30]
For example I have some local file or url.

I want to put it in the container. Is there any way to do it from the script?

something like

```
app.models.container.save('../filepath.jpg', 'container1' , function (err, data) {});

```

?

And similar question. How can I move files between containers?

Thanks

**Comment by richardpringle** [comment]
LoopBack-component-storage exposes a set of methods to REST for file manipulation (uploading, downloading, etc).

To move the files around on the server programmatically, you should be able to use the Node.js File System api
`var fs = require('fs')`

I am going to close the issue as it is over a year old but let me know if that helps!
