### ISSUE TITLE
Not Working with Angular 1.3.x

### ISSUE THREAD

**Issue by ilianaza** [strongloop/loopback-component-storage#35]
The Example-2.0 does not work with Angular version 1.3.0 and above. Looks like (at least in Angular v1.3.6) the *defaultHttpResponseTransform* function has been updated to accept a function "headers" as a 2nd parameter:
```
function defaultHttpResponseTransform(data, headers) {
  if (isString(data)) {
    // strip json vulnerability protection prefix
    data = data.replace(JSON_PROTECTION_PREFIX, '');
    var contentType = headers('Content-Type');
    if ((contentType && contentType.indexOf(APPLICATION_JSON) === 0 && data.trim()) ||
        (JSON_START.test(data) && JSON_END.test(data))) {
      data = fromJson(data);
    }
  }
  return data;
}
```

However, it's called inside *_transformResponse* function in the angular-file-upload.js file without the 2nd parameter:
```
_transformResponse: function (response) {
  $http.defaults.transformResponse.forEach(function (transformFn) {
    response = transformFn(response);
  });
  return response;
}
```

Am I doing something wrong here or the example should be adjusted in some way?

**Comment by richardpringle** [comment]
Hey @ilianaza, did you ever manage to figure this out?

**Comment by ilianaza** [comment]
@richardpringle We never managed to get the Example 2.0 to work with Angular 1.3.0. However, I think adding a second parameter **headers** should do the trick, something along these lines: https://github.com/nervgh/angular-file-upload/blob/v1.1.5/angular-file-upload.js#L407
