### ISSUE TITLE
GET unkown file/container returns 500 instead of 404

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-component-storage#4]
```
GET /containers/does-not-exist

{
  "error": {
    "name": "Error",
    "status": 500,
    "message": "ENOENT, stat '/Users/bajtos/src/loopback/android/test-server/storage/does-not-exist'",
    "errno": 34,
    "code": "ENOENT",
    "path": "/Users/bajtos/src/loopback/android/test-server/storage/does-not-exist",
    "stack": "Error: ENOENT, stat '/Users/bajtos/src/loopback/android/test-server/storage/does-not-exist'"
  }
}
```

**Comment by jaime-franco** [comment]
Hi, Using Amazon S3 i get 500 internal error server with a message 

`
{
  "error": {
    "message": "The specified key does not exist.",
    "code": "NoSuchKey",
    "region": null,
    "time": "2016-05-05T23:06:05.754Z",
    "requestId": "638EDCE6C4A26F92",
    "extendedRequestId": "jQF3rslwLLatYfRPbm4pnJwuCDgUpE+tVcGccULi2m10LylNMuhowUOJlFlBCQDVpv8Vd5NDqdw=",
    "statusCode": 404,
    "retryable": false,
    "retryDelay": 12.993586948141456
  }
}
`

**Comment by superkhau** [comment]
@jaime-franco Please open a new issue with a fulll description of your situation. See https://github.com/strongloop/loopback/wiki/Reporting-issues#bug-report.
