### ISSUE TITLE
FileSystemProvider: Invalid name

### ISSUE THREAD

**Issue by wanqingmiao** [strongloop/loopback-component-storage#40]
I want to upload The whole directory file，so changed the input ,add webkitdirectory:
<input ng-file-select type="file" webkitdirectory multiple
After,could not upload the folder files with the error :FileSystemProvider: Invalid name

**Comment by seriousben** [comment]
Path separators are not allowed by the filesystemprovider ... would be nice if it was. Just making sure we never allow code to write outside of it (I am guessing this is the reason why path.sep is not allowed)

**Comment by raymondfeng** [comment]
@seriousben Yes, it's consistent with other providers. The container/file is a flat structure. Maybe we can maps `x/y/z.txt` to `x$y$z.txt` to avoid such constraints.

**Comment by MiguelGonzalezAravena** [comment]
I have to create my own 'container creator', i use `mkdirp` (It's like mkdir -p in terminal) for create folders or directories, if this not exists, then create the path. 

**container.js**
`
'use strict';
var loopback = require('loopback'),
  path = require('path'),
  fs = require('fs'),
  mkdirp = require('mkdirp'),
  filesPath = path.join(__dirname, '../../' + (require(path.join(__dirname, '../../server/datasources.json')).container.root));

module.exports = function(container) {
  container.create = function(name, cb) {
    let newContainer = path.join(filesPath, name);

    container.createContainer({ name: name }, function() {
      // Verificar si la ruta existe
      fs.stat(newContainer, function(err, stat) {
        // De no existir la ruta, el stat devuelve 'undefined'
        // Si se sabe que no existe, se crea la ruta
        if(typeof stat == 'undefined') {
          mkdirp(newContainer, function (err) {
            if(err) {
              console.error(err);
            } else {
              // Éxito, contenedor creado
              cb(null, { success: { message: 'Contenedor creado con éxito.', container: name } });
            }
          });
        } else {
          // Error, ruta existente
          cb(null, { error: { message: 'El contenedor ya existe.' } });
        }
      });
    });
  };

  container.remoteMethod('create', { 
    http: { path: '/create', verb: 'get' },
    accepts: { arg: 'name', type: 'string' },
    returns: { arg: 'response', type: 'object' },
    description: 'Create containers for user\'s uploads for the application.'
  });
};
`
Add to your **datasources.json**
`
{
[...]
  "container": {
    "name": "container",
    "connector": "loopback-component-storage",
    "provider": "filesystem",
    "root": "./storage"
  },
[...]
}
`

**Comment by MiguelGonzalezAravena** [comment]
I did a fork of this project for you can create Containers with slash, that means that you can create Containers like this/isMy/newContainer, and the plugin do all the work for you. You have to replace slash with `%2F`. All information is in https://github.com/MiguelGonzalezAravena/loopback-component-storage.
The PR is https://github.com/strongloop/loopback-component-storage/pull/217
