### ISSUE TITLE
Failed to apply acl header for amazon s3 upload to make it public- read using rest api

### ISSUE THREAD

**Issue by shivam-dev** [strongloop/loopback-component-storage#45]
Failed to apply acl header for amazon s3 upload to make it public- read using rest api post call

in earlier version of "loopback-component-storage - 1.0.5"

i made the change in module to make it public-read.

var writer = provider.upload({container: container, remote: part.filename, headers: {'x-amz-acl': 'public-read'}});

/lib/storage-handler.js

--- a/lib/storage-handler.js
+++ b/lib/storage-handler.js
@@ -57,7 +57,7 @@ exports.upload = function (provider, req, res, container, cb) {
     if ('content-type' in part.headers) {
       headers['content-type'] = part.headers['content-type'];
     }
-    var writer = provider.upload({container: container, remote: part.filename});
+    var writer = provider.upload({container: container, remote: part.filename, headers: {'x-amz-acl': 'public-read'}});

In new version of module, how can i make acl to public read.

**Comment by raymondfeng** [comment]
Please try v1.3.0
