### ISSUE TITLE
POST file to an nonexistant container throws an uncaught exception and crash my nodejs

### ISSUE THREAD

**Issue by mhoude** [strongloop/loopback-component-storage#46]
Posting a file to a nonexistant container will throw an uncaught exception and crash your server.

ie : POST localhost:3000/test/api/storage/90/upload

crashes the server with this exception : 
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: ENOENT, open 'C:\...\...\storage\logos\sites\90\myfile.jpg'

The API should create the container OR at least respond with a 404 so that we can handle it.

Thanks

**Comment by wiredots01** [comment]
same here.. after upload
events.js:85
      throw er; // Unhandled 'error' event

Error: ENOENT, open '/path_to_file

**Comment by raymondfeng** [comment]
Try 1.5.1 release of loopback-component-storage.

**Comment by Morriz** [comment]
This is still an issue with 1.6.1

**Comment by Morriz** [comment]
btw, I see master at 1.6.0, but npm's latest on 1.6.1...weird
