### ISSUE TITLE
Error 500 in Post method and get,post method listed twice.

### ISSUE THREAD

**Issue by Rikhart** [strongloop/loopback-component-storage#48]
..,
  "storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "provider": "filesystem",
    "root": "storage"
  }...
I have setting up the datasource using slc and JSON following the steps of http://docs.strongloop.com/display/public/LB/Storage+service   then through "loopback arc" I defined a model named "bucket" the problem is when I see trough "API EXPLORER" the methods get and post are listed twice.

![selection_047](https://cloud.githubusercontent.com/assets/1900153/6209035/ce64dbc6-b58e-11e4-8baa-0ad00bddf288.png)

And when I try to create a new bucket I get an error 500.

**Comment by richardpringle** [comment]
Hey @Rikhart, I realize that this issue was not attended in a timely manner, but are you still running into problems? I'm trying to clean up all the old issues right now and would like to close this if the issue is no longer relevant.
