### ISSUE TITLE
POST existing container returns 500

### ISSUE THREAD

**Issue by bajtos** [strongloop/loopback-component-storage#5]
An attempt to create a container with a name that already exists fails with 500. The user should get a different error, most likely a validation error "name must be unique".

```
Error in POST /containers: Error: EEXIST, mkdir '/Users/bajtos/src/loopback/android/test-server/storage/a-container-1392317969686'
```

**Comment by gianlucamov** [comment]
Hi!
Does anyone knows a better mitigation of this bug other than checking between all containers ?
...
app.models.Container.getContainers(function (err, containers) {
            if (containers.some(function(e) { return e.name == containerName; })){
...
thanks a lot
Gianluca
