### ISSUE TITLE
File rename - settings by configuration file

### ISSUE THREAD

**Issue by AaronBedward** [strongloop/loopback-component-storage#52]
Can anybody point me examples of creating a file rename service via config.

My scenario is that I would like to rename files on local for my tests and on amazon for my production.

**Comment by richardpringle** [comment]
Hey @AaronBedward, please post this question in one of the following locations: 
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We are reserving GitHub issues for bug reports and feature requests only. You will get a better response in a more timely manner in one of the above mentioned locations.
