### ISSUE TITLE
Can loopback-component-storage work with iOS client now? 

### ISSUE THREAD

**Issue by bit-jmm** [strongloop/loopback-component-storage#53]
I only find some docs about Android on strongloop. So, are there some examples or docs available about iOS client? Thanks a lot.

**Comment by richardpringle** [comment]
Hey @bit-jmm, please ask any questions on one of the following:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We are reserving GitHub issues for feature requests and bug reports only.

With that said, I have actually never seen any documentation about using component-storage with Android. Would you mind sharing a link?

I am going to close this issue as a question (I will still see the link if you post it), but if you would specifically like certain compatibility features between LoopBack-iOS-SDK and LoopBack-component-storage, please open a new issues with a detailed description of what you would like to see.
