### ISSUE TITLE
Files should be written to disk before calling `afterRemote` hook

### ISSUE THREAD

**Issue by smehrbrodt** [strongloop/loopback-component-storage#56]
I'm using the `afterRemote` hook to create image thumbnails after an image has been uploaded. When I want to access the uploaded file in that hook, the image is not yet completely written to disk and thus I can't create thumbnails without errors.

A workaround is to copy the file and operate on the copied file.
`fs.createReadStream(originalfile).pipe(fs.createWriteStream(copyfile));`
This works, whyever.

However, loopback should make sure that the file is written to disk before calling the `afterRemote` hook.

**Comment by sayden** [comment]
Related with #58

**Comment by vl4dt** [comment]
Hello, I am trying to do something similar, process the file after it has been uploaded, however I went through all the documentation I could find without a clue on how to access the uploaded file, no documentation at all and threw some debugging output in the console to try to figure this out but, no matter what I upload (the upload works fine, testing this with the filesystem), all attributes and objects I receive in the afterRemote arguments are "undefined", some are objects containing more objects that eventually end up "undefined".

I'm new to this framework and don't really have the time to delve deep in the framework inner workings, any pointers would be greatly appreciated.
