### ISSUE TITLE
Giving public access to the file while uploading

### ISSUE THREAD

**Issue by Karabi-Choudhury** [strongloop/loopback-component-storage#60]
I am using the storageAPI to upload a file in s3.How can i give public access to the file?
I am making a call like below
var writer = storageService.uploadStream(folderName, fileName);

**Comment by richardpringle** [comment]
Hey @Karabi-Choudhury, best places to ask questions are as follows: 
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We are actually reserving the issues section on GitHub for feature requests and bug reports only so I'm going to close this issue but I think that the answer lies within the `Container` object, ([you can access it here](https://github.com/strongloop/loopback-example-storage/blob/master/example-2.0/server/models/container.js))

Hopefully that helps! Feel free to carry on the discussion in this issue and I will answer, but it would be better to bring up the question and get help from the full community.

Also, sorry about the delayed response... :disappointed:
