### ISSUE TITLE
slc loopback:datasource misconfigures connector in datasources.json

### ISSUE THREAD

**Issue by Izhaki** [strongloop/loopback-component-storage#65]
When using `slc loopback:datasource` [these docs](http://docs.strongloop.com/display/public/LB/Storage+connector) say:

> At the prompt "Enter the connector name without the loopback-connector- prefix," enter storage.

This creates the following in `datasources.json`:

    "localFS": {
        "name": "localFS",
        "connector": "storage",
    }

However, when testing the api, one gets:

    loopback "Object #<Storage> has no method 'all'"

Which is fixed, based on all of the example on this repository, but changing it `datasources.json` to:

    "localFS": {
        "name": "localFS",
        "connector": "loopback-component-storage",
    }

**Comment by richardpringle** [comment]
Migrated to https://github.com/strongloop/generator-loopback/issues/167
