### ISSUE TITLE
How to create a custom remote method for uploading file ?

### ISSUE THREAD

**Issue by harshil93** [strongloop/loopback-component-storage#66]
I have created the container model as described in the examples. I now have the endpoints which allows me to upload files to container. 

I have a user model. I want to create an remote method api/users/uploadDisplayPic using container model which will allow users to upload jpegs as their display pics. How to write such a remote method. 

Any pointers will be helpful for me ?

**Comment by AlmaasAre** [comment]
Maybe you should try to use the StorageService API instead: http://docs.strongloop.com/display/public/LB/Storage+component+API#storageservice-prototype-upload

**Comment by faustomorales** [comment]
So, just in case someone else stumbles upon this, here's a code snippet. It assumes that the container does not yet exist, so you can add the code to check for a pre-existing container if you like (probably by creating a user to container relation). Hopefully, this helps someone. 

````
module.exports = function(user) {
 user.upload = function(req,res,cb) {
	var Container = user.app.models.Container;
	Container.createContainer({name:user.name},function(err,c) {
	 Container.upload(req,res,{container: c.name},cb)
	});
 }
 user.remoteMethod (
	'upload',
	{
	 http: {path: '/:id/uploadDisplayPic', verb: 'post'},
	 accepts: [
		{arg: 'req', type: 'object', 'http': {source: 'req'}},
		{arg: 'res', type: 'object', 'http': {source: 'res'}}
	 ],
	 returns: {arg: 'status', type: 'string'}
	}
 );
};
````

**Comment by tekand** [comment]
@faustomorales It helped me. ;) Furthermore, I improved it a bit:

```javascript
module.exports = function(Material) {

	Material.upload = function(req, res, material_id, cb) {

		var StorageContainer = Material.app.models.StorageContainer;

		StorageContainer.getContainers(function (err, containers) {
			if (containers.some(function(e) { return e.name == material_id; })) {
				StorageContainer.upload(req, res, {container: material_id}, cb);
			}
			else {
				StorageContainer.createContainer({name: material_id}, function(err, c) {
    				StorageContainer.upload(req, res, {container: c.name}, cb);
    			});
			}
		});
    };

    Material.remoteMethod(
	    'upload',
	    {
	     http: {path: '/:id/upload', verb: 'post'},
	     accepts: [
	        {arg: 'req', type: 'object', 'http': {source: 'req'}},
	        {arg: 'res', type: 'object', 'http': {source: 'res'}},
	        {arg: 'id', type: 'string'}
	     ],
	     returns: {arg: 'status', type: 'string'}
	    }
  	);
};
```

Where StorageContainer is my container and Material is the REST endpoint what I would like to enhance with the possibility to upload a file.

**Comment by Overdrivr** [comment]
@tekand @faustomorales I am looking to do the same thing, but I'm rather confused at your code. Is it working, can you upload files correctly with it ?

What are objects "req" and "res" in your remote method (I understand it's request and response but I'm confused that client has to provide them) ?
When calling the API client-side, what should we provide for such objects ?

**Comment by faustomorales** [comment]
@Overdrivr I recommend you review the documentation on LoopBack [remote methods](https://docs.strongloop.com/display/public/LB/Remote+methods) to understand the parameters that LoopBack provides to remote methods. For client-side code, the implementation will depend on how you develop your front end. If you're using Angular, there are several modules you can use for file uploads.

**Comment by Overdrivr** [comment]
Thanks, I read your code a bit fast, did not see you were using http mapping.

For reference, there is also a good topic on SO that solves this exact question (It's also referenced somewhere in the strongloop docs).

http://stackoverflow.com/questions/28885282/how-to-store-files-with-meta-data-in-loopback

@harshil93 now you have code examples + SO, shall we ask to close this ticket ?

**Comment by richardpringle** [comment]
@harshil93, I am going to close the ticket.

Thanks @tekand and @faustomorales for your example code!

**Comment by luizv** [comment]
@tekand and @faustomorales , hi. 

I'm new to loopback and node, and I can't find the answer for it nowhere else, but suppose it is a simple thing.

It's usual to find this implementation to solve this upload problem, and you both implemented it like: 
```
...
Container.upload(req, res, {container: containerName}, cb).
...
```

But in documentation, the Container.upload method is defined as:
```
upload(req, res, cb) 
```

I'm losing some time trying to discover could i implement something like you two did... When i run my code i got:

> Container.upload(req, res, {container: folder}, cb);
> ReferenceError: cb is not defined.

I need to override the method at the Container.js? How?
Or i need to set this call back (cb) elsewhere? 

Last question, could you comment on what this array in the thirty parameter position ({container: containerName}) are doing exactly? I'm asking this question to understanding better what is happening here.


(For reference, I bump into this SO question:
[http://stackoverflow.com/questions/39889471/loopback-upload-files-from-another-model], but I did not have enough reputation for commenting for directions. Sorry if this kind of question do not fit well here.) 

(And thanks for the snippets posted earlier in this post! :P)

**Comment by luizv** [comment]
Follow up: My bad! I didn't took notice that the snippets posted here are from loopback-storage-service, not loopback-component-storage. All the methods look very similar to me. Now everything makes more sense. 👍

Anyway, should I use this "superseded" api? Or **there is a way to pass this kind of options on loopback-component-storage?** @AlmaasAre who mentioned this API above, or one of the others, maybe you could shed a light on this issue? Thanks again!

**Comment by jackrobertscott** [comment]
The **loopback-component-storage** is a trick.

It's good for one type of circumstance but if you want to do anything more complicated to the file you have uploaded (like resize it or upload it) then using the loopback-component-storage makes life soooooo difficult...

The better way to do it is to use a file extractor like multiparty and then you have the file to do what ever you want from it. I wrote a little post on how to do that here: https://medium.com/@jackscott/upload-files-to-aws-s3-in-loopback-29a3f01119f4

Hope it helps! 😄
