### ISSUE TITLE
crashes, when uploading from HTML-form without choosing a file

### ISSUE THREAD

**Issue by gruzilla** [strongloop/loopback-component-storage#75]
HTML-Form:

``` html
<form id="uploadForm" method="post" enctype="multipart/form-data" action="/api/Containers/conti/upload?access_token=abc">
    <input id="uploadFile" type="file" name="myfile" />
    <input id="uploadFile2" type="file" name="my2ndfile" />
    <button>submit</button>
</form>
```

What i did:
1. choose file for first field
2. submit form WITHOUT choosing a second file

Request created:

```
------WebKitFormBoundaryCTfqzjkAlmhKL5ms
Content-Disposition: form-data; name="myfile"; filename="Example1.png"
Content-Type: image/png


------WebKitFormBoundaryCTfqzjkAlmhKL5ms
Content-Disposition: form-data; name="my2ndfile"; filename=""
Content-Type: application/octet-stream


------WebKitFormBoundaryCTfqzjkAlmhKL5ms--
```

Result on server:

```
FileSystemProvider: Invalid name:
/data/node_modules/loopback/node_modules/continuation-local-storage/context.js:78
  throw exception;
        ^
TypeError: Cannot read property 'on' of undefined
at IncomingForm.form.handlePart (/data/node_modules/loopback-component-storage/lib/storage-handler.js:117:11)
at IncomingForm.onPart (/data/node_modules/loopback-component-storage/node_modules/formidable/lib/incoming_form.js:177:8)
at MultipartParser.parser.onHeadersEnd (/data/node_modules/loopback-component-storage/node_modules/formidable/lib/incoming_form.js:411:10)
at callback (/data/node_modules/loopback-component-storage/node_modules/formidable/lib/multipart_parser.js:102:31)
at MultipartParser.write (/data/node_modules/loopback-component-storage/node_modules/formidable/lib/multipart_parser.js:215:9)
at IncomingForm.write (/data/node_modules/loopback-component-storage/node_modules/formidable/lib/incoming_form.js:157:34)
at IncomingMessage.<anonymous> (/data/node_modules/loopback-component-storage/node_modules/formidable/lib/incoming_form.js:123:12)
at IncomingMessage.<anonymous> (/data/node_modules/loopback/node_modules/continuation-local-storage/context.js:74:17)
at emitOne (events.js:77:13)
at IncomingMessage.emit (events.js:166:7)
```

I suspect the bug might be found here: https://github.com/strongloop/loopback-component-storage/blob/master/lib/storage-handler.js#L33

As far as i can tell, there is no check, if there is actually any binary content in this part of the multipart body.

i don't know if it changes anything, but i use an afterRemote-hook to persist additionally sent metadata.
and i run node via nodemon inside docker.

**Comment by pvazq001** [comment]
I'm having the same issue.

**Comment by mehlleniumfalke** [comment]
+1

**Comment by gruzilla** [comment]
we finally used a workaround concerning uploads using https://www.npmjs.com/package/multer and a custom remote method

**Comment by cfjedimaster** [comment]
Just to add on to this - it looks like there is no easy fix for this either. I added an error handler to my site but it is not used for this error. It looks you you would need to add a beforeRemote('upload') and scan the request ob for an incoming file. Since the Storage component doesn't require a particular name for the file field, you have to look across the entire Form data for any one possible file.

**Comment by casamia918** [comment]
@cfjedimaster  Do you have any idea to write the error handler code? If I use multipart parsing module (like formidable, which used in loopback-component-storage lib script) to check the request contains file, I have to parse multipart form data 2 times (first to check, second to upload). But at the 1st stage, the file comes from client already consumed and this makes server waiting forever. 

I think that the only way is error handling in storage-handler.

**Comment by cfjedimaster** [comment]
Not really. Obviously I had some idea (see comment) about how, just not the real code. ;)

**Comment by casamia918** [comment]
I wrote simple file check code in storage-handler.js. It working.
My module version is 1.8.1

1. Find form.parse method at node_modules/loopback-component-storage/lib/stroage-handler.js
(It's around line 169)

2. Add below code
```
  form.parse(req, function(err, _fields, _files) {
    if (err) {
      console.error(err);
    }

    // My custom code for No-file-uploaded error check
    if(!files.file || !files.file[0].size || (files.file[0].size == 0)) {
      console.error(new Error('No file uploaded'));
      cb(new Error('No file uploaded'));
      return;
    }

    cb && cb(err, {files: files, fields: fields});
  });
```

ref. https://github.com/felixge/node-formidable

**Comment by JiaxiangX** [comment]
I'm surprised no one has mentioned a fix for this after 1 year.
Makes me wonder if Loopback is production ready.

Anyway, I've added a simple fix that works for me:
loopback-storage-component 1.8.1

look for file **node-modules/loopback-component-storage/lib/storage-handler.js**

At line 38:
`if (part.filename === undefined) {`

Add in additional check for part.filename:
`if (part.filename === undefined || part.filename === '') {`

**Comment by loay** [comment]
Fix is merged.
