### ISSUE TITLE
Implementing E-tag support for better caching

### ISSUE THREAD

**Issue by licnep** [strongloop/loopback-component-storage#76]
It would be nice to implement etag support (it shouldn't be too hard): 
https://en.wikipedia.org/wiki/HTTP_ETag

Basically responses should include a "etag" header, which should be an hash of the file (or the time of last edit). 
Then when we get a request for a file with the "If-None-Match" header, we should check if the file hash matches and if it does we should only reply with a "HTTP 304 Not Modified" instead of sending the whole file. 

This is important for files that can be updated, while allowing for caching. 

I could try to implement it myself but I'm not too familiar with the code, and not sure what to use to calculate the hash

**Comment by hermannsblum** [comment]
Any updates in this?
