### ISSUE TITLE
Compress image before upload to provider

### ISSUE THREAD

**Issue by hellsan631** [strongloop/loopback-component-storage#79]
I would love the ability to easily compress an image before its uploaded to a provider, or create a few different versions of the image (different sizes, etc).

I currently use the component storage for several API's that all have image elements to them (avatars, gallery, etc). Usually, I host the files offsite (on amazon or rackspace), so doing the file compression locally to new files isn't an option.

This is also related to #38 (which i would love to have), but if the compression can be accomplished using a 'beforeRemote' hook, i'm still down for that.

So far, i've been trying to tackle the problem by using the 'beforeRemote' hook on 'upload'. [Here is a quick snippet of what I've got.](https://github.com/PraxusGroup/social-gallery/blob/a6e2375212f48281be1edcb6de07cc87b35b72a9/common/models/media.js)

I think i've hit a wall using the beforeRemote method, as i've only found the one 'buffer', and changing it currently causes time-outs.

The only other way I can imagine doing the compression is by compressing the image data in browser using canvas, etc (which I already do a little bit for the upload preview on that project), or creating a fork/new upload method that does some image compression there.

**Comment by raymondfeng** [comment]
I wonder if you need to do something similar as https://github.com/expressjs/compression/blob/master/index.js to wrap the req object to streamline the compression against the incoming http req.
