### ISSUE TITLE
Transcode

### ISSUE THREAD

**Issue by seminice** [strongloop/loopback-component-storage#82]
Im trying to transcode an uploaded video in real time, how can I have an access to the file parts?

**Comment by richardpringle** [comment]
Hey @seminice, please ask any questions in one of  the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

You should get a more timely response. 

[This PR](https://github.com/strongloop/loopback-component-storage/pull/99) should give you an idea. I don't believe that there is currently any documentation on this.
