### ISSUE TITLE
Cannot create new container using rest api

### ISSUE THREAD

**Issue by TonyLuo** [strongloop/loopback-component-storage#83]
The storage service works well when upload files and down files,but  when I try to create a new container using post rest api,  get error message : "Cannot call container.create()". not sure if I use the api correctly.

$http.post('/api/containers/',{name:"test-container"}).success(function (data) {
                    console.log(data);
                })

### datasources.json
"storage": {
    "name": "storage",
    "connector": "loopback-component-storage",
    "provider": "filesystem",
    "root": "./storage"
  }

### model-config.json:
  "container": {
    "dataSource": "storage",
    "public": true
  },

### Error message
{"error":{"name":"Error","status":500,"message":"Cannot call container.create(). The create method has not been setup. The PersistedModel has not been correctly attached to a DataSource!","stack":"Error: Cannot call container.create(). The create method has not been setup. The PersistedModel has not been correctly attached to a DataSource!\n

**Comment by gsarfati** [comment]
+1

**Comment by Westermann** [comment]
+1

**Comment by traptisaxena** [comment]
Facing same problem. Need immediate help

**Comment by shSina** [comment]
container must be a Model not a PersistedModel
should change it on container.json -->  "base": "PersistedModel" --> "base": "Model"

**Comment by thefinnomenon** [comment]
Thanks shSina, that change worked perfectly.

**Comment by denzelwamburu** [comment]
+1
