### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by OnlyRefat** [strongloop/loopback-component-storage#84]
How to check in the ctx.req object that if there is a file or not? I am requesting a multipart form request.  My custom method accepts 

 accepts: [
                { arg: 'ctx', type: 'object', http: { source:'context' } }
            ]
And in the method i want to check if there is a file attached before
 Model.app.models.container.upload(ctx.req,ctx.result,options,function (err,fileObj){});

i tried to console(ctx.req). But the list is huge and hard to find.

Help.

**Comment by mike-aungsan** [comment]
@OnlyRefat  

You found it ?

**Comment by OnlyRefat** [comment]
Yes i did .

**Comment by mike-aungsan** [comment]
New to loopback. Do not understand what is context in http source.
Could you please share?
The only doc I found is this.
https://docs.strongloop.com/display/LB/Using+current+context

**Comment by OnlyRefat** [comment]
I have done a full project in Loopback. So here is what i have gathered. Context is the scenario . It can be differed depending on which type of http post request you are making (multipart/xxx-application/json). And File upload should be done through the container class. And it can be checked whether it has file or not is checking 

Multipart
Model.app.models.container.upload(ctx.req,ctx.result,options,function (err,fileObj){
if(fileObj.files.hasOwnProperty('file'))
// do something
**You can check all the data you have passed with the key name.
});

Content type: xxx-form-data

if your endpoint name is 

Model.endpointname = function(data,cb){

if(data.req.body.parameterName)
// do something
}

Thanks,
Hope it helps.

**Comment by mike-aungsan** [comment]
Many Thanks @OnlyRefat

**Comment by OnlyRefat** [comment]
@mike-aungsan  Feel free to ask me anything regarding loopback :)

**Comment by mike-aungsan** [comment]
Sure. I just pick up a few days ago. So far I am good with Model and Remote Methods. Going to have a look at Relationship and ACL today. :)

**Comment by mike-aungsan** [comment]
How do I get fileObj wihout using container?

**Comment by richardpringle** [comment]
@mike-aungsan looks like this is solved to me!
For future questions, check out the following locations:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

If you post in there, you have the full community at your fingertips. We're trying to reserve the issues sections on GitHub for feature requests and bug reports, so the chances that someone sees your questions and is able to respond in a timely manner is a lot lower.
