### ISSUE TITLE
Upload a file from postman

### ISSUE THREAD

**Issue by karenpio** [strongloop/loopback-component-storage#86]
Hi! I'm having troubles uploading a file. When I consume the endpoint to upload an image (http://0.0.0.0:3000/api/containers/profile_pics/upload) and I select the image to send (Body - form-data) But in the docs there's no information about how the file should be sent. I upload the file with a key "file", but the request never ends. Is there a way to upload an image from postman? Because it's not working for me :\

Thanks

**Comment by TNT-Likely** [comment]
i have the same problem,if you reslove it ,please tell me @karenpio .
in addition i have one more question,how can i convert 'base64 image url' to multipart/form-data?

thanks

**Comment by tanogalego** [comment]
@karenpio you are ok, just use Header "Accept" with value "multipart/form-data", not setting "Content-type". That works for me from Postman. @TNT-Likely

**Comment by richardpringle** [comment]
Looks like this is solved. @karenpio or @TNT-Likely, please re-open the issue and mention me directly if you are still having troubles!

**Comment by sanjaykumarns** [comment]
As you have told, I set the headers and tried the api with "file" as the request param and the base64 encoded data as the value. But the requeswt never ends.
![screenshot from 2017-03-14 10 43 40](https://cloud.githubusercontent.com/assets/6234808/23886797/ab82128a-08a3-11e7-8278-a8af73fe1814.png)
![screenshot from 2017-03-14 10 43 57](https://cloud.githubusercontent.com/assets/6234808/23886800/af013922-08a3-11e7-83a8-31168cbf98c7.png)

What I am missing here?

**Comment by alocvm** [comment]
![image](https://user-images.githubusercontent.com/12836576/41409225-1e83be58-6fde-11e8-9795-ab7afb69c4e5.png)
I'm used headers Accept, it's not working
