### ISSUE TITLE
Support Promises

### ISSUE THREAD

**Issue by gausie** [strongloop/loopback-component-storage#88]
As titled, support Promises in the same style as a Persisted-Model.

**Comment by Morriz** [comment]
Is this watched? Why does this not have a label? I hope it makes it in soon...

**Comment by richardpringle** [comment]
@Morriz, priority remains on the [LoopBack core module](https://github.com/strongloop/loopback). If you could create a new issue and word in such a way that it isn't just applicable to component-storage, it might get a higher priority. 

For now I will keep a feature label on this issue.

**Comment by uniconstructor** [comment]
It's very difficult to use storage component without promises when all core loopback api supports them. Callbacks from storage API make my code look like a mess very quickly. Please consider to approve PR#260.
