### ISSUE TITLE
use angular client sdks,container.upload({container:'containername'},{multipart/form-data})

### ISSUE THREAD

**Issue by TNT-Likely** [strongloop/loopback-component-storage#89]
i want to ask what's the key name of multipart/form-data?

**Comment by richardpringle** [comment]
Hey @TNT-Likely, please ask any questions on one (or more) of the following:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We are reserving the issues section on GitHub for bug reports and feature requests to make it a little more manageable. I don't have an answer for you off the top of my head, so try asking in one of the communities if you still haven't found an answer!

Good luck
