### ISSUE TITLE
Got stuck when uploading a file

### ISSUE THREAD

**Issue by shuai-zh** [strongloop/loopback-component-storage#9]
I added storage service feature to my app like this https://gist.github.com/chocstarfish/10224682,
and used the example code in here https://github.com/strongloop/loopback-storage-service/tree/master/example to test it. 

The problem is when I upload a file, the request is always pending and after a while it throws an error like this:

```
http://localhost:3000/api/containers/container1/upload net::ERR_EMPTY_RESPONSE
```

![image](https://cloud.githubusercontent.com/assets/1223136/2651905/84428360-bf9c-11e3-8264-40c569eef5e5.png)

and the back-end also logs an error:

```
Error: Request aborted
```

I think I am using the latest npm packages, then what is the problem?

**Comment by wiredots01** [comment]
i having the same issue always pending after submit. In what specific file did you remove the bodyParser from? is it in the passport?
