### ISSUE TITLE
not updated depedencies for Node 0.12.7

### ISSUE THREAD

**Issue by rkmax** [strongloop/loopback-component-storage#90]
`engine pkgcloud@0.9.6: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"0.12.7","npm":"3.3.3"})`

**Comment by richardpringle** [comment]
@rkmax I believe that this is no longer relevant as we are now `pkgcloud@^1.1.0`. Please re-open this issue and mention me directly if the problem persists. 

Cheers
