### ISSUE TITLE
Why doesn't it have a location(url)?

### ISSUE THREAD

**Issue by yomybaby** [strongloop/loopback-component-storage#91]
Hi there,

I'm trying to handle files via this component.
In the result of GET files, it doesn't have a location(url) of files.
Is there any special reason?

I just try to find a way to make it have a location.
But I couldn't find where can it be.
How can I do that?

Thanks!

**Comment by richardpringle** [comment]
@yomybaby what do you mean by location, which container the file is in?

For future reference please post questions in one of the following locations for a more timely response:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We're trying to reserve the issues section on GitHub for bug reports and feature requests only to make things a little more manageable. I am going to close this issue as a question but feel free to carry on the discussion with me in the closed issue.

(Although I hope you found your answer a long time ago)

Cheers
