### ISSUE TITLE
Return no content when 404

### ISSUE THREAD

**Issue by Shyri** [strongloop/loopback-component-storage#94]
Hi everyone
I'm trying to figure out how to return nothing when a file requested is not found. I have set a filesystem storage datasource and a Container model with its API. Everything works perfect. But I want to return only 404 error and not the whole error model when a file download request ends up not finding the file.

I am receiving something like this:

```json
{
  "error": {
    "errno": -2,
    "code": "ENOENT",
    "path": "../../storage/mycontainer/myfile.txt"
  }
}
```
I don't like the idea of exposing the path to containers inside my server.
Any thoughts?

Thank you very much

**Comment by richardpringle** [comment]
Hey @Shyri, did you ever figure it out? For future reference, you will probably get a response in a much more timely manner if you post on one (or more) of the following:
- [Google Groups](https://groups.google.com/forum/#!forum/loopbackjs)
- [StackOverflow](http://stackoverflow.com/questions/tagged/loopbackjs+or+strongloop?sort=newest&pageSize=50)
- [Gitter](https://gitter.im/strongloop/loopback) (supported, but we prefer posting to Google Groups so others may benefit from the discussions)

We're trying to reserve the issues section on GitHub for bug reports and feature requests only (although this is kind of a feature request). 

Hopefully this page is useful: https://docs.strongloop.com/display/APIC/Defining+middleware#Definingmiddleware-Error-handlingmiddleware. 

Although, I'm note sure how well it works with component-storage.

I'm going to close this issue as I am hoping that you found your answer, but if you haven't please re-open it and mention me directly. 

Cheers
