### ISSUE TITLE
Can not delete file from uploaded files.

### ISSUE THREAD

**Issue by tukaram-eap** [strongloop/loopback-component-storage#96]
Hi..
  I am trying to delete file, using loopback component storage file system. 
I was uploaded file in structure ->   {container name} / profile--pic/2015/10/13/AS6isdsssss/filename.jpg

when i am trying to delete this file using removeFile method it shows response given below.
{
  "error": {
    "name": "Error",
    "status": 404,
    "message": "Shared class \"Media\" has no method handling DELETE /container.vms/files/profile-pic/55e9a1961c41d6910c73d948/avatar.jpg",
    "statusCode": 404
  }
}

**Comment by raideltorres** [comment]
same error here, but with no file at all

error: {name: "Error", status: 404, message: "Shared class "Category" has no method handling DELETE /",…}
message: "Shared class "Category" has no method handling DELETE /"
name: "Error"
status: 404
statusCode: 404

**Comment by mariohmol** [comment]
similar here.. cant use destroybyid in a normal table

**Comment by Ascarbek** [comment]
same issue.. had to write own remote method to handle the request ((

**Comment by richardpringle** [comment]
Tested this in https://github.com/strongloop/loopback-example-storage (example-2.0) and it worked fine. 

Have you guys tried the latest version @tukaram-eap, @raideltorres, @mariohmol, @Ascarbek?
