### ISSUE TITLE
Upload file without POST request

### ISSUE THREAD

**Issue by arne-s** [strongloop/loopback-component-storage#97]
When uploading files to a container, the upload() method expects a request object. But how can I upload a file that's not coming from a post request but already exists on the filesystem? Do I need to fake a post request?

**Comment by mike-aungsan** [comment]
@arne-s  found solution?

**Comment by arne-s** [comment]
Nope, since I use the filesystem as my storage device for my current project, I worked around it by directly copying the file to the destination folder, which works for now, but I really like to know how to properly use the container methods so I can switch to a different storage device in the future.

**Comment by mike-aungsan** [comment]
Thanks.

**Comment by philippdhh** [comment]
Hi,

I am struggeling with the same problem in this context:

I have a remote method for creating smaller sized versions of existing images. It does the follwing:
- A Remote Method with an image id is called.
- This remote method calls another extern REST server through a REST datasource and sends the image ID as parameter
- The other server now calls a local endpoint of my applicaton to GET the original image. This is returned by calling loopback component storage download method.
- The other REST Server scales down the image and returns the smaller image in the body of the response
- My original remote method receives this response and stores the smaller image in a local variable.

Now I need to upload the smaller image to my storage provider again. But I have no idea about how to utilize loopback component storage for this as there is no request object to pass.

Do you now a simple method to create a new request object from within a remote method (even this seems pretty weird)?

Have you got another idea or solution?

I'd love to pass a file directly to component storage instead of creating a "fake" request.

**Comment by arne-s** [comment]
I've been looking into the current implementation of uploading files to containers, but it requires a lot of work to make this happen since the parsing of the request object and the code to upload the parsed file to the storage device are all in a single method. I can decouple everything but that requires a lot of refactoring and testing of all the current available storage services. And because I don't know the current road map of loopback/strongloop, I'm not going to put a lot of time into it and then have the pull request rejected. 

A temporary solution would be to use a library that accepts a file and makes a post request, see https://www.npmjs.com/package/poster

**Comment by hgouveia** [comment]
needing this functionality too , I'm generating thumbnails and now i want to store them into the cloud storage

**Comment by felipetoffolo1** [comment]
Same here. Any workaround?
I want to upload some thumbnails but i have no idea how to use upload() or uploadStream().
The thumbs are already in my filesystem.

**Comment by felipetoffolo1** [comment]
Soh i got a workaround.
I made a storage model using filesystem named image and another model using s3 provider named container.
After that, when i did a upload to my filesystem i get the image in the folder, convert and send they.

`module.exports = function(Image) {
  var qt = require('quickthumb');
  var path = require('path');
  var fs = require('fs');

  Image.afterRemote('upload', function(ctx, res, next) {

    var container = Image.app.models.Container;
    var file = res.result.files.Filedata[0];

// Definindo paths dos arquivos
    var file_path = "/tmp/storage/" + file.container + "/" + file.name;
    var filemedium_thumb_path = "/tmp/storage/" + file.container + "/thumbmedium/" + file.name;
    var filesmall_thumb_path = "/tmp/storage/" + file.container + "/thumbsmall/" + file.name;

// Send orig size
    var fileNameOrigin = "origin-" + file.name;
    var stream = container.uploadStream(file.container, fileNameOrigin);
    var sendStream = fs.createReadStream(file_path)
    sendStream.pipe(stream);

//Convert and send small size
    qt.convert({
      src: file_path,
      dst: filemedium_thumb_path,
      width: 200
    }, function(err, path) {
      var fileNameMedium = "medium-" + file.name;
      var stream = container.uploadStream(file.container, fileNameMedium);
      var sendStream = fs.createReadStream(filemedium_thumb_path)
      sendStream.pipe(stream);
    });

//Convert and send small size
    qt.convert({
      src: file_path,
      dst: filesmall_thumb_path,
      width: 50
    }, function(err, path) {
      var fileNameSmall = "small-" + file.name;
      var stream = container.uploadStream(file.container, fileNameSmall);
      var sendStream = fs.createReadStream(filesmall_thumb_path)
      sendStream.pipe(stream);
    });

    next();
  });
};
`

Hope to be helpful

**Comment by arne-s** [comment]
If you just want to upload/convert images you could also consider a service like cloudinary.com

**Comment by MarkAndrewJohnson** [comment]
You can also use the S3 signed uploads to create a signature server-side, and have the browser upload direct to S3.  Then you can use something like imgix.net to create variants on the fly.

**Comment by karanssj4** [comment]
I was facing a similar issue. I was creating a pdf at server side which was to be moved to amazon S3. I ended up using poster (https://www.npmjs.com/package/poster) as pointed by @arne-s 


```
const { url, restApiRoot } = app.locals.settings;
const mycontainer = 'CONTAINER-NAME';
const accessToken = 'ACCESS-TOKEN';
const options = {
  uploadUrl: `${url.slice(0, -1)}${restApiRoot}/containers/${mycontainer}/upload?access_token=${accessToken}`,
  method: 'POST',
  fileContentType: 'application/pdf'
  // you can change this to match the mime type of your file
};

poster.post('/path/to/my/pdf/filename.pdf', options, (err, data) => {
  if (!err) {
    console.log(data);
    // data has the response from REST API
  }
});
```
